/**
 * ==========================================================================
 *  GRADE 7 ELA PRE/POST — REPORTING & AUTO-SCORING
 *  Single-file build. Paste this whole file into ONE Apps Script file.
 * ==========================================================================
 *
 *  SETUP
 *  1. Create a Google Sheet. Extensions > Apps Script.
 *  2. Delete whatever is in Code.gs and paste this entire file in its place.
 *  3. Click the gear (Project Settings) and tick
 *     "Show appsscript.json manifest file in editor".
 *     Open appsscript.json and paste in the manifest from
 *     google-apps-script/appsscript.json. (That file is JSON, not script —
 *     it declares which permissions the project needs.)
 *  4. Save, then reload the spreadsheet tab. An "ELA Reporting" menu appears.
 *  5. Run: ELA Reporting > 1. Set up workbook.
 *     Google asks you to authorize on first run. If you see an
 *     "unverified app" screen, click Advanced > Go to (project name).
 *     It is your own script; the permissions are limited to this
 *     spreadsheet, Google Forms, and Google Docs.
 *
 *  WARNING: "Set up workbook" rebuilds all ten sheets and ERASES any scores
 *  already entered. It asks first. Duplicate the spreadsheet before re-running
 *  it once you have live data.
 *
 *  Built to the Georgia Milestones Grade 7 ELA Assessment Blueprint.
 *  Generated by tools/build_apps_script_bundle.py — do not edit this file by
 *  hand; edit the individual .gs sources and re-run that script.
 * ==========================================================================
 */


// ======================================================================
// ===  Config.gs
// ======================================================================

/**
 * Config.gs — single source of truth for the Grade 7 ELA pre/post reporting system.
 *
 * Everything downstream (sheet construction, auto-scoring, student reports) reads
 * from this file. If you change an item's category or point value here, change it
 * in docs/02-Blueprint-Alignment-Matrix.md too, or the two will drift apart.
 */

/** Roster capacity. Raise or lower freely; every formula scales with it. */
var N_STUDENTS = 150;

/** Row geometry — identical on every sheet so student N is always the same row. */
var CAT_ROW = 3;      // reporting-category code for each item column
var MAX_ROW = 4;      // maximum points for each item column
var HDR_ROW = 5;      // column headers
var FIRST_ROW = 6;    // first student row
var LAST_ROW = FIRST_ROW + N_STUDENTS - 1;

var FIRST_ITEM_COL = 3;   // column C

/**
 * Item specification. Order defines column order on the entry sheets.
 *   type: SR    selected response, one key
 *         MP    two parts (includes evidence-based selected response) — 1 pt per part
 *         MS    multiple-select "choose TWO"
 *         MATCH four cells matched to S1 / S2 / B
 *   opts: number of answer choices (used by the Form builder)
 */
var ITEMS = [
  {n: 1,  label: 'Q1',  max: 1, cat: 'I-TEC', std: '7.T.T.1',  exp: '7.T.T.1.a',            dok: 2, trait: '',  type: 'SR',    opts: 4},
  {n: 2,  label: 'Q2',  max: 2, cat: 'I-TEC', std: '7.T.T.1',  exp: '7.T.T.1.b',            dok: 3, trait: '',  type: 'MP',    opts: 4},
  {n: 3,  label: 'Q3',  max: 1, cat: 'I-LNG', std: '7.L.V.3',  exp: '7.L.V.3.b',            dok: 2, trait: '',  type: 'SR',    opts: 4},
  {n: 4,  label: 'Q4',  max: 1, cat: 'I-CSS', std: '7.T.SS.2', exp: '7.T.SS.2.a',           dok: 2, trait: '',  type: 'SR',    opts: 4},
  {n: 5,  label: 'Q5',  max: 1, cat: 'I-TEC', std: '7.T.T.1',  exp: '7.T.T.1.c',            dok: 2, trait: '',  type: 'SR',    opts: 4},
  {n: 6,  label: 'Q6',  max: 1, cat: 'I-TEC', std: '7.T.T.4',  exp: '7.T.T.4.a',            dok: 1, trait: '',  type: 'SR',    opts: 4},
  {n: 7,  label: 'Q7',  max: 2, cat: 'I-TEC', std: '7.T.T.4',  exp: '7.T.T.4.a',            dok: 3, trait: '',  type: 'MP',    opts: 4},
  {n: 8,  label: 'Q8',  max: 2, cat: 'I-TEC', std: '7.T.T.1',  exp: '7.T.T.1.c',            dok: 3, trait: '',  type: 'MS',    opts: 5},
  {n: 9,  label: 'Q9',  max: 1, cat: 'I-PRA', std: '7.T.PM.1', exp: '7.T.PM.1.a',           dok: 2, trait: '',  type: 'SR',    opts: 4},
  {n: 10, label: 'Q10', max: 2, cat: 'I-PRA', std: '7.T.T.1',  exp: '7.T.T.1.d/7.T.PM.1.a', dok: 3, trait: '',  type: 'MP',    opts: 4},
  {n: 11, label: 'Q11', max: 1, cat: 'I-CSS', std: '7.T.SS.1', exp: '7.T.SS.1.a',           dok: 2, trait: '',  type: 'SR',    opts: 4},
  {n: 12, label: 'Q12', max: 1, cat: 'I-TEC', std: '7.T.T.2',  exp: '7.T.T.2.a',            dok: 2, trait: '',  type: 'SR',    opts: 4},
  {n: 13, label: 'Q13', max: 1, cat: 'I-TEC', std: '7.T.T.2',  exp: '7.T.T.2.a',            dok: 2, trait: '',  type: 'SR',    opts: 4},
  {n: 14, label: 'Q14', max: 1, cat: 'I-LNG', std: '7.L.V.2',  exp: '7.L.V.2.a',            dok: 1, trait: '',  type: 'SR',    opts: 4},
  {n: 15, label: 'Q15', max: 1, cat: 'I-LNG', std: '7.L.V.2',  exp: '7.L.V.2.b',            dok: 2, trait: '',  type: 'SR',    opts: 4},
  {n: 16, label: 'Q16', max: 2, cat: 'I-CSS', std: '7.T.C.1',  exp: '7.T.C.1.a',            dok: 3, trait: '',  type: 'MP',    opts: 4},
  {n: 17, label: 'Q17', max: 1, cat: 'I-TEC', std: '7.T.T.3',  exp: '7.T.T.3.a',            dok: 2, trait: '',  type: 'SR',    opts: 4},
  {n: 18, label: 'Q18', max: 2, cat: 'I-TEC', std: '7.T.T.3',  exp: '7.T.T.3.a',            dok: 3, trait: '',  type: 'MP',    opts: 4},
  {n: 19, label: 'Q19', max: 1, cat: 'I-LNG', std: '7.L.V.3',  exp: '7.L.V.3.c',            dok: 2, trait: '',  type: 'SR',    opts: 4},
  {n: 20, label: 'Q20', max: 2, cat: 'I-CSS', std: '7.T.C.2',  exp: '7.T.C.2.a/b',          dok: 3, trait: '',  type: 'MP',    opts: 4},
  {n: 21, label: 'Q21', max: 2, cat: 'I-LNG', std: '7.L.GC.2', exp: '7.L.GC.2.a',           dok: 2, trait: '',  type: 'MP',    opts: 4},
  {n: 22, label: 'Q22', max: 2, cat: 'I-TEC', std: '7.T.T.2',  exp: '7.T.T.2.b',            dok: 3, trait: '',  type: 'MATCH', opts: 3},
  {n: 23, label: 'Q23', max: 1, cat: 'I-PRA', std: '7.T.RA.2', exp: '7.T.RA.2.b',           dok: 2, trait: '',  type: 'SR',    opts: 4},
  {n: 24, label: 'Q24', max: 2, cat: 'I-PRA', std: '7.T.RA.2', exp: '7.T.RA.2.a',           dok: 2, trait: '',  type: 'MP',    opts: 4},
  {n: 25, label: 'Q25', max: 1, cat: 'C-CSS', std: '7.T.SS.1', exp: '7.T.SS.1.d',           dok: 2, trait: '1', type: 'SR',    opts: 4},
  {n: 26, label: 'Q26', max: 1, cat: 'C-TEC', std: '7.T.T.3',  exp: '7.T.T.3.c',            dok: 2, trait: '2', type: 'SR',    opts: 4},
  {n: 27, label: 'Q27', max: 2, cat: 'C-TEC', std: '7.T.T.3',  exp: '7.T.T.3.c/7.T.RA.2.c', dok: 3, trait: '2', type: 'MS',    opts: 4},
  {n: 28, label: 'Q28', max: 2, cat: 'C-TEC', std: '7.T.T.2',  exp: '7.T.T.2.d',            dok: 2, trait: '2', type: 'MP',    opts: 4},
  {n: 29, label: 'Q29', max: 1, cat: 'C-TEC', std: '7.T.T.3',  exp: '7.T.T.3.c',            dok: 2, trait: '2', type: 'SR',    opts: 4},
  {n: 30, label: 'Q30', max: 2, cat: 'C-CSS', std: '7.T.SS.1', exp: '7.T.SS.1.c',           dok: 3, trait: '1', type: 'MP',    opts: 4},
  {n: 31, label: 'Q31', max: 1, cat: 'C-CSS', std: '7.T.SS.2', exp: '7.T.SS.2.c',           dok: 2, trait: '1', type: 'SR',    opts: 4},
  {n: 32, label: 'Q32', max: 1, cat: 'C-LNG', std: '7.L.GC.2', exp: '7.L.GC.2.b',           dok: 2, trait: '3', type: 'SR',    opts: 4},
  {n: 33, label: 'Q33', max: 2, cat: 'C-LNG', std: '7.L.GC.2', exp: '7.L.GC.2.c',           dok: 2, trait: '3', type: 'MS',    opts: 5},
  {n: 34, label: 'Q34', max: 1, cat: 'C-LNG', std: '7.L.GC.2', exp: '7.L.GC.2.d',           dok: 2, trait: '3', type: 'SR',    opts: 4},
  {n: 35, label: 'Q35', max: 1, cat: 'C-LNG', std: '7.L.GC.1', exp: 'GUM (Master Gr 6)',    dok: 1, trait: '3', type: 'SR',    opts: 4},
  {n: 36, label: 'Q36', max: 1, cat: 'C-LNG', std: '7.L.V.2',  exp: '7.L.V.2.d',            dok: 2, trait: '3', type: 'SR',    opts: 4},
  {n: 37, label: 'Q37', max: 1, cat: 'C-TEC', std: '7.T.RA.2', exp: '7.T.RA.2.c',           dok: 2, trait: '2', type: 'SR',    opts: 4},
  {n: 38, label: 'Q38', max: 1, cat: 'C-CSS', std: '7.T.SS.1', exp: '7.T.SS.1.d',           dok: 2, trait: '1', type: 'SR',    opts: 4},
  {n: 39, label: 'Q39_T1', max: 3, cat: 'C-CSS', std: 'Essay Trait 1', exp: 'Purpose & Organization',       dok: 3, trait: '1', type: 'ESSAY'},
  {n: 39, label: 'Q39_T2', max: 3, cat: 'C-TEC', std: 'Essay Trait 2', exp: 'Evidence & Elaboration',       dok: 3, trait: '2', type: 'ESSAY'},
  {n: 39, label: 'Q39_T3', max: 2, cat: 'C-LNG', std: 'Essay Trait 3', exp: 'Language Usage & Conventions', dok: 3, trait: '3', type: 'ESSAY'}
];

var N_ITEMS = ITEMS.length;                               // 41 columns
var LAST_ITEM_COL = FIRST_ITEM_COL + N_ITEMS - 1;         // AQ
var COND_COL = LAST_ITEM_COL + 1;                         // AR — essay condition code
var TOTAL_COL = LAST_ITEM_COL + 2;                        // AS — total

/** Scored items only (excludes the three essay traits). Used by the Form builder. */
var SCORED_ITEMS = ITEMS.filter(function (it) { return it.type !== 'ESSAY'; });

/**
 * Answer keys. Verified against assessments/Form-A-Answer-Key.md and
 * assessments/Form-B-Answer-Key.md.
 *   SR    -> 'B'
 *   MP    -> ['PartA', 'PartB']
 *   MS    -> ['A','C']  (the two correct choices)
 *   MATCH -> ['S1','S2','B','B']  (cells a, b, c, d)
 */
var KEYS = {
  A: {
    1: 'B',  2: ['B', 'C'],  3: 'D',  4: 'C',  5: 'A',  6: 'D',  7: ['A', 'B'],
    8: ['A', 'C'],  9: 'A', 10: ['C', 'B'], 11: 'C', 12: 'B', 13: 'D', 14: 'A',
    15: 'C', 16: ['B', 'B'], 17: 'B', 18: ['B', 'B'], 19: 'C', 20: ['B', 'A'],
    21: ['C', 'B'], 22: ['S1', 'S2', 'B', 'B'], 23: 'A', 24: ['B', 'C'],
    25: 'D', 26: 'B', 27: ['A', 'D'], 28: ['C', 'B'], 29: 'A', 30: ['D', 'A'],
    31: 'B', 32: 'C', 33: ['A', 'D'], 34: 'D', 35: 'A', 36: 'B', 37: 'C', 38: 'D'
  },
  B: {
    1: 'A',  2: ['C', 'D'],  3: 'C',  4: 'A',  5: 'B',  6: 'A',  7: ['B', 'C'],
    8: ['A', 'C'],  9: 'C', 10: ['C', 'C'], 11: 'D', 12: 'A', 13: 'B', 14: 'D',
    15: 'B', 16: ['C', 'B'], 17: 'D', 18: ['B', 'C'], 19: 'A', 20: ['C', 'C'],
    21: ['B', 'B'], 22: ['S1', 'S2', 'B', 'B'], 23: 'B', 24: ['C', 'C'],
    25: 'A', 26: 'D', 27: ['A', 'D'], 28: ['D', 'C'], 29: 'C', 30: ['B', 'C'],
    31: 'D', 32: 'B', 33: ['B', 'D'], 34: 'C', 35: 'D', 36: 'C', 37: 'B', 38: 'C'
  }
};

/** Reporting categories — max points replicate the Georgia Milestones blueprint exactly. */
var CATEGORIES = [
  {code: 'I-CSS', name: 'Interpreting — Context, Structure & Style', max: 6,
   focus: "Author's purpose and audience; perspective, tone, and credibility; how structure and figurative language shape meaning",
   start: "Model 'why did the author build it this way?' on short texts. Standards 7.T.C.1.a, 7.T.C.2.a-b, 7.T.SS.1.a, 7.T.SS.2.a."},
  {code: 'I-TEC', name: 'Interpreting — Techniques', max: 16,
   focus: 'Narrative, expository, argumentative, and poetic technique analysis; theme; claim and counterclaim; comparing two authors on one topic',
   start: 'Largest category on the test (16 pts). Split by technique type before grouping — narrative gaps and argumentative gaps need different lessons.'},
  {code: 'I-PRA', name: 'Interpreting — Periods & Movements + Research', max: 6,
   focus: 'Myth and adaptation analysis; comparing fiction to an account of the same material; source credibility, relevance, and bibliographic information',
   start: 'Pair every literary text with its source myth or historical account. Teach credibility as a two-part judgment: credible AND relevant to the question.'},
  {code: 'I-LNG', name: 'Interpreting — Language (Grammar & Vocabulary)', max: 6,
   focus: 'Context clues beyond the sentence; Greek and Latin roots; part of speech as a meaning clue; connotation; reading syntax',
   start: 'Daily morphology routine plus "read the next sentence" modeling for multiple-meaning words. Standards 7.L.V.2, 7.L.V.3, 7.L.GC.2.a.'},
  {code: 'C-CSS', name: 'Constructing — Context, Structure & Style', max: 8,
   focus: 'Introductions that establish a claim; cohesive structure; transitions that name relationships; style for a target audience; conclusions that finalize',
   start: 'Peer Revision Task routine, Trait 1 guided questions. Start with claim-writing and conclusion-writing; transitions after.'},
  {code: 'C-TEC', name: 'Constructing — Techniques', max: 10,
   focus: 'Reasons that support the claim; evidence from MULTIPLE sources; elaboration in the student’s own words; counterclaims; crediting sources',
   start: 'Explicit evidence-to-elaboration instruction. Sentence stems: "This matters because…" Reuse test items 27 and 28 as warm-ups.'},
  {code: 'C-LNG', name: 'Constructing — Language (Grammar & Vocabulary)', max: 8,
   focus: 'Sentence variety; consistent verb tense; active voice; misplaced and dangling modifiers; punctuation; precise word choice',
   start: 'Sentence combining plus targeted GUM work on rows marked M at Grades 6-7. Standards 7.L.GC.2.b-d, 7.L.GC.1.'}
];

var SET_CAT_FIRST = 28;   // Settings row of the first category in the lookup table

var LEVELS = ['Beginning Learner', 'Developing Learner', 'Proficient Learner', 'Distinguished Learner'];

var SHEETS = {
  start: 'START HERE',
  settings: 'Settings',
  roster: 'Roster',
  pre: 'Pre-Test Entry',
  post: 'Post-Test Entry',
  report: 'Student Report',
  dash: 'Class Dashboard',
  items: 'Item Analysis',
  groups: 'Intervention Groups',
  coverage: 'Standards Coverage'
};

var COLORS = {
  navy: '#1F3864', blue: '#2E5C8A', light: '#DCE6F1', band: '#F2F5FA',
  input: '#FFF2CC', grey: '#E8E8E8',
  green: '#C6EFCE', amber: '#FFEB9C', red: '#FFC7CE',
  inputText: '#0000FF', muted: '#595959'
};

/** Convert a 1-based column index to an A1 column letter. */
function colA1(n) {
  var s = '';
  while (n > 0) {
    var m = (n - 1) % 26;
    s = String.fromCharCode(65 + m) + s;
    n = (n - m - 1) / 26;
  }
  return s;
}

var CL_FIRST = colA1(FIRST_ITEM_COL);   // C
var CL_LAST = colA1(LAST_ITEM_COL);     // AQ
var CL_COND = colA1(COND_COL);          // AR
var CL_TOTAL = colA1(TOTAL_COL);        // AS

// ======================================================================
// ===  BuildSheets.gs
// ======================================================================

/**
 * BuildSheets.gs — constructs the whole reporting workbook inside Google Sheets.
 *
 * Every computed cell is a live formula, so the sheet recalculates when a teacher
 * edits a score, a cut point, or a threshold. Formula logic matches the Excel
 * build in reporting/build_reporting_workbook.py, which was verified cell by cell
 * against independently computed values.
 *
 * Run buildAll() once from the menu: ELA Reporting ▸ Set up workbook.
 */

// ---- Student Report column map -------------------------------------------
var R_ID = 1, R_NAME = 2, R_PER = 3;
var R_PRE_T = 4, R_PRE_P = 5, R_PRE_L = 6;
var R_POST_T = 7, R_POST_P = 8, R_POST_L = 9;
var R_GAIN = 10, R_PCTPOSS = 11, R_RCI = 12, R_REL = 13, R_TGT = 14;
var R_PRECAT = 15;                       // O..U
var R_POSTCAT = R_PRECAT + 7;            // V..AB
var R_CHG = R_POSTCAT + 7;               // AC..AI
var R_WEAK1 = R_CHG + 7;                 // AJ
var R_WEAK2 = R_WEAK1 + 1;               // AK
var R_NEAR = R_WEAK2 + 1;                // AL
var R_ESSAY = R_NEAR + 1;                // AM
var R_FOCUS = R_ESSAY + 1;               // AN
var R_SQ_PRE = R_FOCUS + 2;              // AP
var R_SQ_POST = R_SQ_PRE + 1;            // AQ

var PRE_CAT_COLS = [], POST_CAT_COLS = [], CHG_CAT_COLS = [];
for (var _i = 0; _i < 7; _i++) {
  PRE_CAT_COLS.push(colA1(R_PRECAT + _i));
  POST_CAT_COLS.push(colA1(R_POSTCAT + _i));
  CHG_CAT_COLS.push(colA1(R_CHG + _i));
}

// Frozen-column counts. Any full-width merged band on these sheets must be
// split at this boundary — see bandMerge_().
var FREEZE_ROSTER = 3;   // ID, last name, first name stay visible
var FREEZE_ENTRY  = 2;   // ID and student name stay visible across 41 item columns
var FREEZE_REPORT = 3;   // ID, name, period stay visible
var FREEZE_GROUPS = 2;   // ID and student name stay visible across the heat map

// ---- helpers --------------------------------------------------------------

function sheetNamed_(ss, name) {
  var sh = ss.getSheetByName(name);
  if (sh) { sh.clear(); sh.clearConditionalFormatRules(); }
  else { sh = ss.insertSheet(name); }
  return sh;
}

/**
 * Merge a horizontal band, splitting it at the frozen-column boundary.
 *
 * Google rejects a frozen region containing only PART of a merged cell:
 *   "you can't freeze columns which contain only part of a merged cell"
 * A banner spanning A:AN on a sheet with 3 frozen columns triggers exactly
 * that. Splitting it into A:C and D:AN keeps the frozen region whole and looks
 * identical, because both blocks carry the same fill.
 *
 * Returns the full band range so formatting can be applied uniformly.
 */
function bandMerge_(sh, row, width, freezeAt) {
  if (freezeAt && freezeAt > 0 && freezeAt < width) {
    sh.getRange(row, 1, 1, freezeAt).merge();
    sh.getRange(row, freezeAt + 1, 1, width - freezeAt).merge();
  } else {
    sh.getRange(row, 1, 1, width).merge();
  }
  return sh.getRange(row, 1, 1, width);
}

function titleBar_(sh, text, width, freezeAt) {
  bandMerge_(sh, 1, width, freezeAt)
    .setBackground(COLORS.navy).setFontColor('#FFFFFF')
    .setFontFamily('Arial').setFontSize(14).setFontWeight('bold')
    .setVerticalAlignment('middle');
  sh.getRange(1, 1).setValue(text);
  sh.setRowHeight(1, 34);
}

function subtitle_(sh, row, text, width, freezeAt) {
  bandMerge_(sh, row, width, freezeAt)
    .setFontFamily('Arial').setFontSize(9)
    .setFontStyle('italic').setFontColor(COLORS.muted).setWrap(true);
  sh.getRange(row, 1).setValue(text);
}

function sectionBar_(sh, row, text, width, freezeAt) {
  bandMerge_(sh, row, width, freezeAt)
    .setBackground(COLORS.light).setFontColor(COLORS.navy)
    .setFontFamily('Arial').setFontSize(11).setFontWeight('bold');
  sh.getRange(row, 1).setValue(text);
}

/** A wrapped full-width note, split at the freeze boundary. */
function noteBand_(sh, row, width, text, freezeAt) {
  bandMerge_(sh, row, width, freezeAt)
    .setFontSize(9).setFontStyle('italic').setFontColor(COLORS.muted)
    .setWrap(true).setVerticalAlignment('top');
  sh.getRange(row, 1).setValue(text);
}

function headerRow_(sh, row, col, values) {
  sh.getRange(row, col, 1, values.length).setValues([values])
    .setBackground(COLORS.blue).setFontColor('#FFFFFF')
    .setFontFamily('Arial').setFontSize(9).setFontWeight('bold')
    .setHorizontalAlignment('center').setVerticalAlignment('middle')
    .setWrap(true).setBorder(true, true, true, true, true, true);
}

function addRule_(sh, ranges, formula, bg, fontColor) {
  var b = SpreadsheetApp.newConditionalFormatRule()
    .whenFormulaSatisfied(formula).setBackground(bg).setRanges(ranges);
  if (fontColor) b = b.setFontColor(fontColor);
  var rules = sh.getConditionalFormatRules();
  rules.push(b.build());
  sh.setConditionalFormatRules(rules);
}

// ---- main -----------------------------------------------------------------

function buildAll() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var ui = SpreadsheetApp.getUi();
  var resp = ui.alert('Set up reporting workbook',
    'This rebuilds all ten sheets. Any scores already entered on the entry sheets will be ERASED.\n\n' +
    'Continue?', ui.ButtonSet.YES_NO);
  if (resp !== ui.Button.YES) return;

  buildStart_(ss);
  buildSettings_(ss);
  buildRoster_(ss);
  buildEntry_(ss, SHEETS.pre, 'FORM A');
  buildEntry_(ss, SHEETS.post, 'FORM B');
  buildStudentReport_(ss);
  buildDashboard_(ss);
  buildItemAnalysis_(ss);
  buildGroups_(ss);
  buildCoverage_(ss);

  var order = [SHEETS.start, SHEETS.settings, SHEETS.roster, SHEETS.pre, SHEETS.post,
               SHEETS.report, SHEETS.dash, SHEETS.items, SHEETS.groups, SHEETS.coverage];
  order.forEach(function (n, i) {
    var sh = ss.getSheetByName(n);
    ss.setActiveSheet(sh); ss.moveActiveSheet(i + 1);
  });
  var def = ss.getSheetByName('Sheet1');
  if (def && ss.getSheets().length > 1) ss.deleteSheet(def);

  ss.setActiveSheet(ss.getSheetByName(SHEETS.start));
  ui.alert('Done', 'Workbook built. Start on the "START HERE" sheet.', ui.ButtonSet.OK);
}

// ---- START HERE -----------------------------------------------------------

function buildStart_(ss) {
  var sh = sheetNamed_(ss, SHEETS.start);
  sh.setHiddenGridlines(true);
  titleBar_(sh, 'Grade 7 ELA Pre/Post Assessment — Results Reporting', 4);
  sh.setColumnWidth(1, 30); sh.setColumnWidth(2, 240); sh.setColumnWidth(3, 700);

  var rows = [
    ['SECTION', 'Do this, in this order', ''],
    ['', '1.  Roster', 'Enter your students. Yellow cells are inputs; everything else is a formula. Row 6 holds an example — overwrite it.'],
    ['', '2.  Pre-Test Entry', 'After Form A, enter points earned per item. Enter 0 for a wrong answer — a blank means "not tested".'],
    ['', '3.  Student Report', 'Computed the moment you finish entering.'],
    ['', '4.  Intervention Groups', 'Group rosters build themselves. Read them and teach.'],
    ['', '5.  Post-Test Entry', 'After Form B in the spring, enter scores the same way.'],
    ['', '6.  Class Dashboard', 'Growth, effect size, and level movement, filterable by class period.'],
    ['SECTION', 'Auto-scoring from a Google Form (optional)', ''],
    ['', 'Create the answer sheet', 'ELA Reporting ▸ Create answer-sheet Form ▸ Form A. Students read the printed booklet and record answers in the Form.'],
    ['', 'Scoring', 'Responses score automatically on submit — partial credit included. Or run ELA Reporting ▸ Score Form responses now.'],
    ['', 'The essay is never auto-scored', 'Enter the three trait scores by hand in the Q39_T1 / T2 / T3 columns. A rubric score is a professional judgment.'],
    ['SECTION', 'Cell colors', ''],
    ['', 'Yellow', 'You type here. The only cells you should edit.'],
    ['', 'White / grey', 'Formulas. Editing one breaks that student’s report.'],
    ['', 'Blue text', 'Values you may deliberately change (cut scores, thresholds) on the Settings sheet.'],
    ['SECTION', 'Three things to know before reporting any of this', ''],
    ['', 'Category scores are small', 'A category rests on as few as 6 points. Treat a low category percent as a HYPOTHESIS to confirm against student work — never as a diagnosis on its own.'],
    ['', 'Not every gain is real', 'The Reliable Change Index says whether an individual gain exceeds measurement error. Report smaller gains as class-level movement, not student growth.'],
    ['', 'Cut scores are provisional', 'Set by content review, not a state standard-setting panel. Instructional triage — NOT a prediction of a student’s Georgia Milestones level.'],
    ['SECTION', 'Source of truth', ''],
    ['', '', 'Georgia’s K-12 ELA Standards, Grade 7 (May 2023) · Georgia Milestones Grade 7 ELA Assessment Blueprint (August 2025) · Draft Grade 7 ELA Achievement Level Descriptors (October 2025) · Georgia Milestones Grade 7 Eight-Point, Three-Trait Writing Rubric (August 2026) · Grade 7 Classroom Peer Revision Guidance (February 2026).']
  ];
  var r = 3;
  rows.forEach(function (row) {
    if (row[0] === 'SECTION') {
      sectionBar_(sh, r, row[1], 3);
    } else {
      if (row[1]) sh.getRange(r, 2).setValue(row[1]).setFontWeight('bold').setFontFamily('Arial').setFontSize(10).setWrap(true).setVerticalAlignment('top');
      sh.getRange(r, 3).setValue(row[2]).setFontFamily('Arial').setFontSize(10).setWrap(true).setVerticalAlignment('top');
    }
    r++;
  });
}

// ---- Settings -------------------------------------------------------------

function buildSettings_(ss) {
  var sh = sheetNamed_(ss, SHEETS.settings);
  sh.setHiddenGridlines(true);
  titleBar_(sh, 'Settings — cut scores, thresholds, and the intervention lookup table', 5);
  subtitle_(sh, 2, 'Blue values are editable. Every formula in this workbook reads from these cells, so changing one here updates every report.', 5);
  [340, 100, 90, 430, 430].forEach(function (w, i) { sh.setColumnWidth(i + 1, w); });

  function setting(row, label, value, note, fmt, isFormula) {
    sh.getRange(row, 1).setValue(label).setFontFamily('Arial').setFontSize(10);
    var c = sh.getRange(row, 2).setValue(value)
      .setHorizontalAlignment('center').setBorder(true, true, true, true, false, false)
      .setFontFamily('Arial').setFontSize(10);
    if (isFormula) c.setBackground(COLORS.grey).setFontWeight('bold');
    else c.setBackground(COLORS.input).setFontColor(COLORS.inputText);
    if (fmt) c.setNumberFormat(fmt);
    sh.getRange(row, 4).setValue(note).setFontFamily('Arial').setFontSize(9)
      .setFontStyle('italic').setFontColor(COLORS.muted).setWrap(true);
  }

  sectionBar_(sh, 4, 'Achievement level cut scores  (raw points out of 60)', 5);
  setting(5, 'Developing Learner — minimum raw score', 30, 'Below this a student is a Beginning Learner. Default = 50% of 60.');
  setting(6, 'Proficient Learner — minimum raw score', 39, 'Default = 65% of 60.');
  setting(7, 'Distinguished Learner — minimum raw score', 49, 'Default = 82% of 60.');
  setting(8, 'Total points possible', 60, 'Change only if you shorten the instrument.');

  sectionBar_(sh, 10, 'Category mastery thresholds  (percent of category points)', 5);
  setting(11, 'Mastered — minimum percent', 0.80, 'At or above: maintain through spiral review.', '0%');
  setting(12, 'Approaching — minimum percent', 0.60, 'Between this and Mastered: small-group instruction. Below: explicit reteaching.', '0%');

  sectionBar_(sh, 14, 'Growth measurement', 5);
  setting(15, 'Individual growth target (raw points)', 9, 'About half a standard deviation. Set BELOW the reliable-change threshold so it works as a goal, not a statistical claim.');
  setting(16, 'Assumed reliability (Cronbach’s alpha)', 0.85, 'Replace with the value computed on the Item Analysis sheet once you have a full class of data.', '0.00');
  setting(17, 'Standard error of measurement (computed)',
    "=IFERROR(ROUND(STDEV('" + SHEETS.report + "'!$D$" + FIRST_ROW + ":$D$" + LAST_ROW + ")*SQRT(1-$B$16),2),\"\")",
    'SD of pre-test scores × SQRT(1 − reliability). Populates once pre-test data is entered.', '0.00', true);
  setting(18, 'Reliable change threshold (raw points)',
    '=IFERROR(ROUND($B$17*SQRT(2)*1.96,1),"")',
    'A gain at or above this is statistically reliable for an individual student (95% confidence). Smaller gains may be measurement noise.', '0.0', true);

  sectionBar_(sh, 20, 'Scoring quality (enter after double-scoring the essays)', 5);
  setting(21, 'Essay double-scoring exact-agreement rate', '', 'Below 70%, do not report individual essay growth — report class-level trait movement only.', '0%');
  setting(22, 'Number of essays double-scored', '', 'Target: at least 20% of papers.');

  sectionBar_(sh, 24, 'Reporting category reference and intervention lookup', 5);
  subtitle_(sh, 25, 'Column C max points replicate the Georgia Milestones Grade 7 ELA blueprint exactly. Columns D and E feed the Recommended Focus column on the Student Report.', 5);
  headerRow_(sh, 27, 1, ['Code', 'Category', 'Max pts', 'Primary instructional focus', 'Where to start']);

  var vals = CATEGORIES.map(function (c) { return [c.code, c.name, c.max, c.focus, c.start]; });
  sh.getRange(SET_CAT_FIRST, 1, vals.length, 5).setValues(vals)
    .setFontFamily('Arial').setFontSize(9).setWrap(true).setVerticalAlignment('top')
    .setBorder(true, true, true, true, true, true);
  sh.getRange(SET_CAT_FIRST, 1, vals.length, 1).setFontWeight('bold').setHorizontalAlignment('center');
  sh.getRange(SET_CAT_FIRST, 3, vals.length, 1).setHorizontalAlignment('center');

  var totRow = SET_CAT_FIRST + CATEGORIES.length;
  sh.getRange(totRow, 2).setValue('TOTAL').setFontWeight('bold').setHorizontalAlignment('right');
  sh.getRange(totRow, 3).setFormula('=SUM(C' + SET_CAT_FIRST + ':C' + (totRow - 1) + ')')
    .setFontWeight('bold').setHorizontalAlignment('center');

  // Class-period filter helper used by the Class Dashboard.
  sh.getRange('Y1').setValue('Helper: class-period filter used by the Class Dashboard')
    .setFontSize(9).setFontStyle('italic').setFontColor(COLORS.muted);
  sh.getRange('Z1').setFormula("=IF('" + SHEETS.dash + "'!$B$4=\"\",\"*\",'" + SHEETS.dash + "'!$B$4)");
}

// ---- Roster ---------------------------------------------------------------

function buildRoster_(ss) {
  var sh = sheetNamed_(ss, SHEETS.roster);
  sh.setHiddenGridlines(true);
  titleBar_(sh, 'Roster', 9, FREEZE_ROSTER);
  subtitle_(sh, 2, 'Every yellow cell is an input. Row 6 is an example — overwrite it. Student order here fixes the row order on every other sheet.', 9, FREEZE_ROSTER);
  sh.getRange(3, 1).setFormula('="Students on roster: "&COUNTA(C' + FIRST_ROW + ':C' + LAST_ROW + ')').setFontWeight('bold');

  var cols = ['Student ID', 'Last Name', 'First Name', 'Class Period', 'Form Order',
              'Accommodations', 'EL', 'SWD', 'Gifted'];
  var widths = [90, 120, 110, 90, 95, 190, 50, 50, 60];
  headerRow_(sh, HDR_ROW, 1, cols);
  widths.forEach(function (w, i) { sh.setColumnWidth(i + 1, w); });

  sh.getRange(FIRST_ROW, 1, 1, 9)
    .setValues([['7001', 'Example', 'Student', '1st', 'A then B', 'None', 'N', 'N', 'N']]);
  sh.getRange(FIRST_ROW, 1, N_STUDENTS, 9)
    .setBackground(COLORS.input).setFontColor(COLORS.inputText)
    .setFontFamily('Arial').setFontSize(10)
    .setBorder(true, true, true, true, true, true);
  sh.getRange(FIRST_ROW, 4, N_STUDENTS, 6).setHorizontalAlignment('center');

  sh.getRange(FIRST_ROW, 5, N_STUDENTS, 1).setDataValidation(
    SpreadsheetApp.newDataValidation().requireValueInList(['A then B', 'B then A'], true).build());
  sh.getRange(FIRST_ROW, 7, N_STUDENTS, 3).setDataValidation(
    SpreadsheetApp.newDataValidation().requireValueInList(['Y', 'N'], true).build());

  sh.setFrozenRows(HDR_ROW);
  sh.setFrozenColumns(FREEZE_ROSTER);
}

// ---- Entry sheets ---------------------------------------------------------

function buildEntry_(ss, name, formLabel) {
  var sh = sheetNamed_(ss, name);
  sh.setHiddenGridlines(true);
  titleBar_(sh, name + ' — ' + formLabel, TOTAL_COL, FREEZE_ENTRY);
  subtitle_(sh, 2, 'Enter POINTS EARNED per item. Enter 0 for a wrong answer — a blank means "not tested" and removes the student from the statistics. ' +
    'Row 3 shows the reporting category; row 4 shows the maximum points.', TOTAL_COL, FREEZE_ENTRY);

  sh.getRange(CAT_ROW, 1).setValue('Category →').setFontSize(9).setFontStyle('italic').setHorizontalAlignment('right');
  sh.getRange(MAX_ROW, 1).setValue('Max points →').setFontSize(9).setFontStyle('italic').setHorizontalAlignment('right');

  headerRow_(sh, HDR_ROW, 1, ['Student ID', 'Student Name']);
  sh.setColumnWidth(1, 85); sh.setColumnWidth(2, 165);

  var cats = [], maxes = [], labels = [];
  ITEMS.forEach(function (it) { cats.push(it.cat); maxes.push(it.max); labels.push(it.label); });

  sh.getRange(CAT_ROW, FIRST_ITEM_COL, 1, N_ITEMS).setValues([cats])
    .setBackground(COLORS.light).setFontSize(8).setHorizontalAlignment('center')
    .setBorder(true, true, true, true, true, true);
  sh.getRange(MAX_ROW, FIRST_ITEM_COL, 1, N_ITEMS).setValues([maxes])
    .setBackground(COLORS.grey).setFontSize(9).setFontWeight('bold')
    .setHorizontalAlignment('center').setBorder(true, true, true, true, true, true);
  headerRow_(sh, HDR_ROW, FIRST_ITEM_COL, labels);
  for (var i = 0; i < N_ITEMS; i++) sh.setColumnWidth(FIRST_ITEM_COL + i, 42);

  headerRow_(sh, HDR_ROW, COND_COL, ['Essay Cond Code']);
  headerRow_(sh, HDR_ROW, TOTAL_COL, ['TOTAL']);
  sh.setColumnWidth(COND_COL, 80); sh.setColumnWidth(TOTAL_COL, 65);
  sh.getRange(MAX_ROW, TOTAL_COL).setFormula('=SUM(' + CL_FIRST + MAX_ROW + ':' + CL_LAST + MAX_ROW + ')')
    .setBackground(COLORS.grey).setFontWeight('bold').setHorizontalAlignment('center');

  var idF = [], nameF = [], totF = [];
  for (var r = FIRST_ROW; r <= LAST_ROW; r++) {
    idF.push(["=IF(" + SHEETS.roster + "!$A" + r + "=\"\",\"\"," + SHEETS.roster + "!$A" + r + ")"]);
    nameF.push(["=IF(" + SHEETS.roster + "!$B" + r + "=\"\",\"\"," + SHEETS.roster + "!$C" + r + "&\" \"&" + SHEETS.roster + "!$B" + r + ")"]);
    totF.push(["=IF(COUNT(" + CL_FIRST + r + ":" + CL_LAST + r + ")=0,\"\",SUM(" + CL_FIRST + r + ":" + CL_LAST + r + "))"]);
  }
  sh.getRange(FIRST_ROW, 1, N_STUDENTS, 1).setFormulas(idF).setHorizontalAlignment('center').setFontSize(9);
  sh.getRange(FIRST_ROW, 2, N_STUDENTS, 1).setFormulas(nameF).setFontSize(9);
  sh.getRange(FIRST_ROW, TOTAL_COL, N_STUDENTS, 1).setFormulas(totF)
    .setFontWeight('bold').setHorizontalAlignment('center');

  var entry = sh.getRange(FIRST_ROW, FIRST_ITEM_COL, N_STUDENTS, N_ITEMS + 1);
  entry.setBackground(COLORS.input).setFontColor(COLORS.inputText)
    .setHorizontalAlignment('center').setFontFamily('Arial').setFontSize(9)
    .setBorder(true, true, true, true, true, true);
  sh.getRange(FIRST_ROW, COND_COL, N_STUDENTS, 1).setDataValidation(
    SpreadsheetApp.newDataValidation().requireValueInList(['A', 'B', 'C', 'D', 'E'], true).build());

  // Flag any entry above the item maximum.
  addRule_(sh, [sh.getRange(FIRST_ROW, FIRST_ITEM_COL, N_STUDENTS, N_ITEMS)],
    '=AND(' + CL_FIRST + FIRST_ROW + '<>"",' + CL_FIRST + FIRST_ROW + '>' + CL_FIRST + '$' + MAX_ROW + ')',
    COLORS.red, '#9C0006');

  sh.setFrozenRows(HDR_ROW);
  sh.setFrozenColumns(FREEZE_ENTRY);
}

// ---- Student Report -------------------------------------------------------

function buildStudentReport_(ss) {
  var sh = sheetNamed_(ss, SHEETS.report);
  sh.setHiddenGridlines(true);
  titleBar_(sh, 'Student Report — individual profiles, growth, and recommended focus', R_FOCUS, FREEZE_REPORT);
  subtitle_(sh, 2, 'Every cell here is computed. "NEAR CUT" means the score is within one standard error of a level boundary — for those students trust the ' +
    'category profile and your own classroom evidence, not the level label.', R_FOCUS, FREEZE_REPORT);

  function banner(c1, c2, text, color) {
    sh.getRange(3, c1, 1, c2 - c1 + 1).merge().setValue(text)
      .setBackground(color).setFontColor('#FFFFFF').setFontSize(9)
      .setFontWeight('bold').setHorizontalAlignment('center');
  }
  banner(R_PRE_T, R_PRE_L, 'PRE-TEST (Form A)', '#7B7B7B');
  banner(R_POST_T, R_POST_L, 'POST-TEST (Form B)', '#4472A8');
  banner(R_GAIN, R_TGT, 'GROWTH', '#548235');
  banner(R_PRECAT, R_PRECAT + 6, 'CATEGORY % — PRE', '#7B7B7B');
  banner(R_POSTCAT, R_POSTCAT + 6, 'CATEGORY % — POST', '#4472A8');
  banner(R_CHG, R_CHG + 6, 'CATEGORY CHANGE (percentage points)', '#548235');
  banner(R_WEAK1, R_FOCUS, 'ACTION', '#A6531C');

  // Row 4 carries the category codes; INDEX/MATCH reads it to name the weakest area.
  var codes = CATEGORIES.map(function (c) { return c.code; });
  [R_PRECAT, R_POSTCAT, R_CHG].forEach(function (base) {
    sh.getRange(4, base, 1, 7).setValues([codes])
      .setBackground(COLORS.light).setFontSize(8).setHorizontalAlignment('center');
  });

  headerRow_(sh, HDR_ROW, 1, ['Student ID', 'Student Name', 'Period',
    'Total', '%', 'Level', 'Total', '%', 'Level',
    'Raw gain', '% of possible gain', 'RCI', 'Reliable change?', 'Met target?']);
  [85, 155, 60, 55, 55, 135, 55, 55, 135, 60, 75, 55, 80, 70].forEach(function (w, i) { sh.setColumnWidth(i + 1, w); });
  [R_PRECAT, R_POSTCAT, R_CHG].forEach(function (base) {
    headerRow_(sh, HDR_ROW, base, codes);
    for (var i = 0; i < 7; i++) sh.setColumnWidth(base + i, 52);
  });
  headerRow_(sh, HDR_ROW, R_WEAK1, ['Weakest category', '2nd weakest', 'Near cut?', 'Essay flag', 'Recommended focus']);
  [95, 90, 75, 120, 460].forEach(function (w, i) { sh.setColumnWidth(R_WEAK1 + i, w); });

  var PRE = "'" + SHEETS.pre + "'", POST = "'" + SHEETS.post + "'", ROS = SHEETS.roster;
  var CAT_HDR_PRE = '$' + PRE_CAT_COLS[0] + '$4:$' + PRE_CAT_COLS[6] + '$4';
  var CAT_HDR_POST = '$' + POST_CAT_COLS[0] + '$4:$' + POST_CAT_COLS[6] + '$4';

  var block = [], sq = [];
  for (var r = FIRST_ROW; r <= LAST_ROW; r++) {
    var named = ROS + '!$B' + r + '<>""';
    var preHas = 'COUNT(' + PRE + '!$' + CL_FIRST + r + ':$' + CL_LAST + r + ')>0';
    var postHas = 'COUNT(' + POST + '!$' + CL_FIRST + r + ':$' + CL_LAST + r + ')>0';
    var row = [];

    row.push('=IF(' + ROS + '!$A' + r + '="","",' + ROS + '!$A' + r + ')');
    row.push('=IF(' + named + ',' + ROS + '!$C' + r + '&" "&' + ROS + '!$B' + r + ',"")');
    row.push('=IF(' + named + ',' + ROS + '!$D' + r + ',"")');

    row.push('=IF(AND(' + named + ',' + preHas + '),' + PRE + '!$' + CL_TOTAL + r + ',"")');
    row.push('=IFERROR(D' + r + '/' + SHEETS.settings + '!$B$8,"")');
    row.push(levelFormula_('D' + r));
    row.push('=IF(AND(' + named + ',' + postHas + '),' + POST + '!$' + CL_TOTAL + r + ',"")');
    row.push('=IFERROR(G' + r + '/' + SHEETS.settings + '!$B$8,"")');
    row.push(levelFormula_('G' + r));

    row.push('=IF(OR(D' + r + '="",G' + r + '=""),"",G' + r + '-D' + r + ')');
    // Percent-of-possible gain is undefined for a flat or declining score.
    row.push('=IFERROR(IF(OR(J' + r + '="",J' + r + '<=0),"",(G' + r + '-D' + r + ')/(' + SHEETS.settings + '!$B$8-D' + r + ')),"")');
    row.push('=IFERROR(IF(J' + r + '="","",(G' + r + '-D' + r + ')/(' + SHEETS.settings + '!$B$17*SQRT(2))),"")');
    row.push('=IF(L' + r + '="","",IF(ABS(L' + r + ')>=1.96,"Yes","No"))');
    row.push('=IF(J' + r + '="","",IF(J' + r + '>=' + SHEETS.settings + '!$B$15,"Yes","No"))');

    for (var i = 0; i < 7; i++) {
      var sr = SET_CAT_FIRST + i;
      row.push('=IFERROR(IF($D' + r + '="","",SUMIF(' + PRE + '!$' + CL_FIRST + '$' + CAT_ROW + ':$' + CL_LAST + '$' + CAT_ROW +
        ',' + SHEETS.settings + '!$A$' + sr + ',' + PRE + '!$' + CL_FIRST + r + ':$' + CL_LAST + r + ')/' + SHEETS.settings + '!$C$' + sr + '),"")');
    }
    for (var i2 = 0; i2 < 7; i2++) {
      var sr2 = SET_CAT_FIRST + i2;
      row.push('=IFERROR(IF($G' + r + '="","",SUMIF(' + POST + '!$' + CL_FIRST + '$' + CAT_ROW + ':$' + CL_LAST + '$' + CAT_ROW +
        ',' + SHEETS.settings + '!$A$' + sr2 + ',' + POST + '!$' + CL_FIRST + r + ':$' + CL_LAST + r + ')/' + SHEETS.settings + '!$C$' + sr2 + '),"")');
    }
    for (var i3 = 0; i3 < 7; i3++) {
      var pc = PRE_CAT_COLS[i3], oc = POST_CAT_COLS[i3];
      row.push('=IF(OR(' + pc + r + '="",' + oc + r + '=""),"",' + oc + r + '-' + pc + r + ')');
    }

    var pr = '$' + PRE_CAT_COLS[0] + r + ':$' + PRE_CAT_COLS[6] + r;
    var po = '$' + POST_CAT_COLS[0] + r + ':$' + POST_CAT_COLS[6] + r;
    row.push('=IFERROR(IF($G' + r + '<>"",INDEX(' + CAT_HDR_POST + ',MATCH(MIN(' + po + '),' + po + ',0)),' +
             'IF($D' + r + '<>"",INDEX(' + CAT_HDR_PRE + ',MATCH(MIN(' + pr + '),' + pr + ',0)),"")),"")');
    row.push('=IFERROR(IF($G' + r + '<>"",INDEX(' + CAT_HDR_POST + ',MATCH(SMALL(' + po + ',2),' + po + ',0)),' +
             'IF($D' + r + '<>"",INDEX(' + CAT_HDR_PRE + ',MATCH(SMALL(' + pr + ',2),' + pr + ',0)),"")),"")');
    row.push('=IF(OR(G' + r + '="",' + SHEETS.settings + '!$B$17=""),"",IF(OR(ABS(G' + r + '-' + SHEETS.settings + '!$B$5)<=' + SHEETS.settings + '!$B$17,' +
             'ABS(G' + r + '-' + SHEETS.settings + '!$B$6)<=' + SHEETS.settings + '!$B$17,ABS(G' + r + '-' + SHEETS.settings + '!$B$7)<=' + SHEETS.settings + '!$B$17),"NEAR CUT",""))');
    row.push('=IF(' + POST + '!$' + CL_COND + r + '<>"","Post essay: code "&' + POST + '!$' + CL_COND + r +
             ',IF(' + PRE + '!$' + CL_COND + r + '<>"","Pre essay: code "&' + PRE + '!$' + CL_COND + r + ',""))');
    row.push('=IFERROR(IF($' + colA1(R_WEAK1) + r + '="","",INDEX(' + SHEETS.settings + '!$D$' + SET_CAT_FIRST + ':$D$' + (SET_CAT_FIRST + 6) +
             ',MATCH($' + colA1(R_WEAK1) + r + ',' + SHEETS.settings + '!$A$' + SET_CAT_FIRST + ':$A$' + (SET_CAT_FIRST + 6) + ',0))),"")');

    block.push(row);
    sq.push(['=IF(D' + r + '="","",D' + r + '^2)', '=IF(G' + r + '="","",G' + r + '^2)']);
  }

  sh.getRange(FIRST_ROW, 1, N_STUDENTS, R_FOCUS).setFormulas(block)
    .setFontFamily('Arial').setFontSize(9).setBorder(true, true, true, true, true, true);
  sh.getRange(FIRST_ROW, R_SQ_PRE, N_STUDENTS, 2).setFormulas(sq);
  sh.getRange(HDR_ROW, R_SQ_PRE, 1, 2).setValues([['helper: pre^2', 'helper: post^2']])
    .setFontSize(8).setFontStyle('italic');
  sh.hideColumns(R_SQ_PRE, 2);

  sh.getRange(FIRST_ROW, R_PRE_P, N_STUDENTS, 1).setNumberFormat('0%').setHorizontalAlignment('center');
  sh.getRange(FIRST_ROW, R_POST_P, N_STUDENTS, 1).setNumberFormat('0%').setHorizontalAlignment('center');
  sh.getRange(FIRST_ROW, R_PCTPOSS, N_STUDENTS, 1).setNumberFormat('0%').setHorizontalAlignment('center');
  sh.getRange(FIRST_ROW, R_PRECAT, N_STUDENTS, 21).setNumberFormat('0%').setHorizontalAlignment('center');
  sh.getRange(FIRST_ROW, R_RCI, N_STUDENTS, 1).setNumberFormat('0.00').setHorizontalAlignment('center');
  [R_ID, R_PER, R_PRE_T, R_POST_T, R_GAIN, R_REL, R_TGT, R_NEAR, R_WEAK1, R_WEAK2]
    .forEach(function (c) { sh.getRange(FIRST_ROW, c, N_STUDENTS, 1).setHorizontalAlignment('center'); });
  [R_PRE_T, R_POST_T, R_GAIN].forEach(function (c) { sh.getRange(FIRST_ROW, c, N_STUDENTS, 1).setFontWeight('bold'); });
  sh.getRange(FIRST_ROW, R_FOCUS, N_STUDENTS, 1).setWrap(true).setVerticalAlignment('top');

  var catRanges = [sh.getRange(FIRST_ROW, R_PRECAT, N_STUDENTS, 7),
                   sh.getRange(FIRST_ROW, R_POSTCAT, N_STUDENTS, 7)];
  var first = colA1(R_PRECAT) + FIRST_ROW, firstPost = colA1(R_POSTCAT) + FIRST_ROW;
  addRule_(sh, [catRanges[0]], '=AND(ISNUMBER(' + first + '),' + first + '>=' + SHEETS.settings + '!$B$11)', COLORS.green);
  addRule_(sh, [catRanges[0]], '=AND(ISNUMBER(' + first + '),' + first + '>=' + SHEETS.settings + '!$B$12)', COLORS.amber);
  addRule_(sh, [catRanges[0]], '=AND(ISNUMBER(' + first + '),' + first + '<' + SHEETS.settings + '!$B$12)', COLORS.red);
  addRule_(sh, [catRanges[1]], '=AND(ISNUMBER(' + firstPost + '),' + firstPost + '>=' + SHEETS.settings + '!$B$11)', COLORS.green);
  addRule_(sh, [catRanges[1]], '=AND(ISNUMBER(' + firstPost + '),' + firstPost + '>=' + SHEETS.settings + '!$B$12)', COLORS.amber);
  addRule_(sh, [catRanges[1]], '=AND(ISNUMBER(' + firstPost + '),' + firstPost + '<' + SHEETS.settings + '!$B$12)', COLORS.red);

  var chgRange = sh.getRange(FIRST_ROW, R_CHG, N_STUDENTS, 7);
  var chgRules = sh.getConditionalFormatRules();
  chgRules.push(SpreadsheetApp.newConditionalFormatRule()
    .setGradientMinpointWithValue('#F8696B', SpreadsheetApp.InterpolationType.NUMBER, '-0.3')
    .setGradientMidpointWithValue('#FFFFFF', SpreadsheetApp.InterpolationType.NUMBER, '0')
    .setGradientMaxpointWithValue('#63BE7B', SpreadsheetApp.InterpolationType.NUMBER, '0.3')
    .setRanges([chgRange]).build());
  sh.setConditionalFormatRules(chgRules);

  addRule_(sh, [sh.getRange(FIRST_ROW, R_NEAR, N_STUDENTS, 1)],
    '=' + colA1(R_NEAR) + FIRST_ROW + '="NEAR CUT"', COLORS.amber, '#7F6000');
  addRule_(sh, [sh.getRange(FIRST_ROW, R_REL, N_STUDENTS, 1)], '=' + colA1(R_REL) + FIRST_ROW + '="Yes"', COLORS.green);
  addRule_(sh, [sh.getRange(FIRST_ROW, R_TGT, N_STUDENTS, 1)], '=' + colA1(R_TGT) + FIRST_ROW + '="Yes"', COLORS.green);

  sh.setFrozenRows(HDR_ROW);
  sh.setFrozenColumns(FREEZE_REPORT);
}

function levelFormula_(cell) {
  var S = SHEETS.settings;
  return '=IF(' + cell + '="","",IF(' + cell + '>=' + S + '!$B$7,"' + LEVELS[3] + '",' +
         'IF(' + cell + '>=' + S + '!$B$6,"' + LEVELS[2] + '",' +
         'IF(' + cell + '>=' + S + '!$B$5,"' + LEVELS[1] + '","' + LEVELS[0] + '"))))';
}

// ======================================================================
// ===  BuildSheets2.gs
// ======================================================================

/**
 * BuildSheets2.gs — Class Dashboard, Item Analysis, Intervention Groups,
 * Standards Coverage.
 *
 * The Intervention Groups sheet uses TEXTJOIN + FILTER to build group rosters
 * automatically. That is a genuine Google Sheets advantage: the Excel version
 * asks the teacher to sort a column by hand, while here the group lists write
 * themselves and update as scores change.
 */

function buildDashboard_(ss) {
  var sh = sheetNamed_(ss, SHEETS.dash);
  sh.setHiddenGridlines(true);
  titleBar_(sh, 'Class Dashboard', 7);
  subtitle_(sh, 2, 'Type a class period in cell B4 to filter every statistic on this sheet to that period. Leave B4 blank for all students.', 7);
  [330, 110, 110, 110, 120, 130, 200].forEach(function (w, i) { sh.setColumnWidth(i + 1, w); });

  sh.getRange(4, 1).setValue('Filter to class period (blank = all):')
    .setFontWeight('bold').setHorizontalAlignment('right');
  sh.getRange(4, 2).setBackground(COLORS.input).setFontColor(COLORS.inputText)
    .setHorizontalAlignment('center').setBorder(true, true, true, true, false, false);

  var REP = "'" + SHEETS.report + "'";
  var S = SHEETS.settings;
  var PER = S + '!$Z$1';
  var PRE_T = REP + '!$D$' + FIRST_ROW + ':$D$' + LAST_ROW;
  var POST_T = REP + '!$G$' + FIRST_ROW + ':$G$' + LAST_ROW;
  var PER_R = REP + '!$C$' + FIRST_ROW + ':$C$' + LAST_ROW;
  var SQ_PRE = REP + '!$' + colA1(R_SQ_PRE) + '$' + FIRST_ROW + ':$' + colA1(R_SQ_PRE) + '$' + LAST_ROW;
  var SQ_POST = REP + '!$' + colA1(R_SQ_POST) + '$' + FIRST_ROW + ':$' + colA1(R_SQ_POST) + '$' + LAST_ROW;

  sectionBar_(sh, 6, 'Overall performance', 7);
  headerRow_(sh, 7, 1, ['', 'Pre-Test', 'Post-Test', 'Change']);

  var stats = [
    ['Students with scores',
     '=COUNTIFS(' + PER_R + ',' + PER + ',' + PRE_T + ',">=0")',
     '=COUNTIFS(' + PER_R + ',' + PER + ',' + POST_T + ',">=0")', '', '0'],
    ['Mean raw score (of 60)',
     '=IFERROR(AVERAGEIFS(' + PRE_T + ',' + PER_R + ',' + PER + '),"")',
     '=IFERROR(AVERAGEIFS(' + POST_T + ',' + PER_R + ',' + PER + '),"")',
     '=IFERROR(C9-B9,"")', '0.0'],
    ['Mean percent', '=IFERROR(B9/' + S + '!$B$8,"")', '=IFERROR(C9/' + S + '!$B$8,"")',
     '=IFERROR(C10-B10,"")', '0%'],
    // Conditional SD without an array formula: SQRT((Sum(x^2) - n*mean^2)/(n-1))
    ['Standard deviation',
     '=IFERROR(SQRT((SUMIFS(' + SQ_PRE + ',' + PER_R + ',' + PER + ')-B8*B9^2)/(B8-1)),"")',
     '=IFERROR(SQRT((SUMIFS(' + SQ_POST + ',' + PER_R + ',' + PER + ')-C8*C9^2)/(C8-1)),"")', '', '0.0'],
    ['Lowest score',
     '=IFERROR(MINIFS(' + PRE_T + ',' + PER_R + ',' + PER + '),"")',
     '=IFERROR(MINIFS(' + POST_T + ',' + PER_R + ',' + PER + '),"")', '', '0'],
    ['Highest score',
     '=IFERROR(MAXIFS(' + PRE_T + ',' + PER_R + ',' + PER + '),"")',
     '=IFERROR(MAXIFS(' + POST_T + ',' + PER_R + ',' + PER + '),"")', '', '0']
  ];
  stats.forEach(function (row, i) {
    var r = 8 + i;
    sh.getRange(r, 1).setValue(row[0]).setFontFamily('Arial').setFontSize(10);
    sh.getRange(r, 2, 1, 3).setValues([[row[1], row[2], row[3]]])
      .setNumberFormat(row[4]).setHorizontalAlignment('center')
      .setBorder(true, true, true, true, true, true).setFontFamily('Arial').setFontSize(10);
  });

  sh.getRange(15, 1).setValue("Class effect size (Cohen's d)").setFontWeight('bold');
  sh.getRange(15, 2).setFormula('=IFERROR((C9-B9)/SQRT((B11^2+C11^2)/2),"")')
    .setNumberFormat('0.00').setFontWeight('bold').setHorizontalAlignment('center')
    .setBorder(true, true, true, true, false, false);
  sh.getRange(15, 3).setFormula('=IFERROR(IF(B15="","",IF(B15>=0.7,"Strong year",' +
    'IF(B15>=0.4,"Solid year",IF(B15>=0.2,"Modest","Below expectation")))),"")')
    .setFontStyle('italic').setFontSize(9);
  sh.getRange(15, 4).setValue('Middle-grades ELA benchmarks: 0.40 solid, 0.70 strong')
    .setFontStyle('italic').setFontSize(9).setFontColor(COLORS.muted);

  sectionBar_(sh, 17, 'Achievement level distribution', 7);
  headerRow_(sh, 18, 1, ['Achievement level', 'Pre — n', 'Pre — %', 'Post — n', 'Post — %', 'Change in n']);
  LEVELS.forEach(function (lv, i) {
    var r = 19 + i;
    sh.getRange(r, 1).setValue(lv).setFontFamily('Arial').setFontSize(10);
    sh.getRange(r, 2, 1, 5).setValues([[
      '=COUNTIFS(' + PER_R + ',' + PER + ',' + REP + '!$F$' + FIRST_ROW + ':$F$' + LAST_ROW + ',"' + lv + '")',
      '=IFERROR(B' + r + '/SUM($B$19:$B$22),"")',
      '=COUNTIFS(' + PER_R + ',' + PER + ',' + REP + '!$I$' + FIRST_ROW + ':$I$' + LAST_ROW + ',"' + lv + '")',
      '=IFERROR(D' + r + '/SUM($D$19:$D$22),"")',
      '=D' + r + '-B' + r
    ]]).setHorizontalAlignment('center').setBorder(true, true, true, true, true, true);
    sh.getRange(r, 3).setNumberFormat('0%');
    sh.getRange(r, 5).setNumberFormat('0%');
  });

  sectionBar_(sh, 24, 'Reporting category performance', 7);
  headerRow_(sh, 25, 1, ['Reporting category', 'Max pts', 'Pre — mean %', 'Post — mean %',
                         'Change', "Students 'Not Yet' (post)", 'Whole-class reteach?']);
  CATEGORIES.forEach(function (c, i) {
    var r = 26 + i;
    var pc = REP + '!$' + PRE_CAT_COLS[i] + '$' + FIRST_ROW + ':$' + PRE_CAT_COLS[i] + '$' + LAST_ROW;
    var oc = REP + '!$' + POST_CAT_COLS[i] + '$' + FIRST_ROW + ':$' + POST_CAT_COLS[i] + '$' + LAST_ROW;
    sh.getRange(r, 1).setValue(c.code + ' — ' + c.name).setFontFamily('Arial').setFontSize(10);
    sh.getRange(r, 2, 1, 6).setValues([[
      c.max,
      '=IFERROR(AVERAGEIFS(' + pc + ',' + PER_R + ',' + PER + ',' + pc + ',">=0"),"")',
      '=IFERROR(AVERAGEIFS(' + oc + ',' + PER_R + ',' + PER + ',' + oc + ',">=0"),"")',
      '=IFERROR(D' + r + '-C' + r + ',"")',
      '=COUNTIFS(' + PER_R + ',' + PER + ',' + oc + ',"<"&' + S + '!$B$12,' + oc + ',">=0")',
      '=IF(C' + r + '="","",IF(F' + r + '>=0.4*MAX(1,COUNTIFS(' + PER_R + ',' + PER + ',' + POST_T + ',">=0")),' +
        '"YES — reteach to whole class","No — small group"))'
    ]]).setHorizontalAlignment('center').setBorder(true, true, true, true, true, true)
      .setFontFamily('Arial').setFontSize(10);
    sh.getRange(r, 3, 1, 3).setNumberFormat('0%');
    sh.getRange(r, 7).setWrap(true);
  });
  addRule_(sh, [sh.getRange(26, 7, CATEGORIES.length, 1)], '=LEFT($G26,3)="YES"', COLORS.red, '#9C0006');

  sectionBar_(sh, 34, 'Growth summary', 7);
  var growth = [
    ['Students with both pre and post scores',
     '=COUNTIFS(' + PER_R + ',' + PER + ',' + REP + '!$J$' + FIRST_ROW + ':$J$' + LAST_ROW + ',">=-999")', '0'],
    ['Students meeting the growth target',
     '=COUNTIFS(' + PER_R + ',' + PER + ',' + REP + '!$N$' + FIRST_ROW + ':$N$' + LAST_ROW + ',"Yes")', '0'],
    ['Percent meeting the growth target', '=IFERROR(B36/B35,"")', '0%'],
    ['Students with statistically reliable change',
     '=COUNTIFS(' + PER_R + ',' + PER + ',' + REP + '!$M$' + FIRST_ROW + ':$M$' + LAST_ROW + ',"Yes")', '0'],
    ['Students who declined (negative gain)',
     '=COUNTIFS(' + PER_R + ',' + PER + ',' + REP + '!$J$' + FIRST_ROW + ':$J$' + LAST_ROW + ',"<0")', '0'],
    ['Students within one SEM of a cut score (post)',
     '=COUNTIFS(' + PER_R + ',' + PER + ',' + REP + '!$' + colA1(R_NEAR) + '$' + FIRST_ROW + ':$' + colA1(R_NEAR) + '$' + LAST_ROW + ',"NEAR CUT")', '0']
  ];
  growth.forEach(function (g, i) {
    var r = 35 + i;
    sh.getRange(r, 1).setValue(g[0]).setFontFamily('Arial').setFontSize(10);
    sh.getRange(r, 2).setFormula(g[1]).setNumberFormat(g[2]).setFontWeight('bold')
      .setHorizontalAlignment('center').setBorder(true, true, true, true, false, false);
  });

  sh.getRange(42, 1, 2, 7).merge().setValue(
    'Read the growth summary in this order: (1) effect size for the class, (2) percent meeting the growth target, ' +
    '(3) students with reliable change. A student below the reliable-change threshold has not demonstrated individually ' +
    'measurable growth — say so plainly rather than reporting the raw gain as if it were.')
    .setFontSize(9).setFontStyle('italic').setFontColor(COLORS.muted).setWrap(true).setVerticalAlignment('top');
}

// ---- Item Analysis --------------------------------------------------------

function buildItemAnalysis_(ss) {
  var sh = sheetNamed_(ss, SHEETS.items);
  sh.setHiddenGridlines(true);
  titleBar_(sh, 'Item Analysis — difficulty, discrimination, and reliability', 14);
  subtitle_(sh, 2, 'p-value = mean score ÷ maximum points. Discrimination is the correlation between the item score and the student’s total. ' +
    'An item below 0.20 is not distinguishing stronger from weaker readers and should be reviewed before the next administration.', 14);

  headerRow_(sh, HDR_ROW, 1, ['Item', 'Max', 'Category', 'Standard', 'Expectation', 'DOK', 'Trait',
    'Pre mean', 'Pre p-value', 'Post mean', 'Post p-value', 'Change in p', 'Discrimination (pre)', 'Flag']);
  [70, 45, 70, 105, 175, 45, 45, 70, 80, 70, 80, 75, 95, 230]
    .forEach(function (w, i) { sh.setColumnWidth(i + 1, w); });

  var PRE = "'" + SHEETS.pre + "'", POST = "'" + SHEETS.post + "'";
  var preTot = PRE + '!$' + CL_TOTAL + '$' + FIRST_ROW + ':$' + CL_TOTAL + '$' + LAST_ROW;
  var rows = [], helper = [];

  ITEMS.forEach(function (it, i) {
    var r = FIRST_ROW + i;
    var L = colA1(FIRST_ITEM_COL + i);
    var preRng = PRE + '!$' + L + '$' + FIRST_ROW + ':$' + L + '$' + LAST_ROW;
    var postRng = POST + '!$' + L + '$' + FIRST_ROW + ':$' + L + '$' + LAST_ROW;
    rows.push([it.label, it.max, it.cat, it.std, it.exp, it.dok, it.trait,
      '=IFERROR(AVERAGE(' + preRng + '),"")',
      '=IFERROR(H' + r + '/$B' + r + ',"")',
      '=IFERROR(AVERAGE(' + postRng + '),"")',
      '=IFERROR(J' + r + '/$B' + r + ',"")',
      '=IFERROR(K' + r + '-I' + r + ',"")',
      '=IFERROR(CORREL(' + preRng + ',' + preTot + '),"")',
      '=IF(I' + r + '="","",IF(I' + r + '<0.25,"Very difficult — check key and instruction",' +
        'IF(I' + r + '>0.9,"Very easy — little information",' +
        'IF(AND(M' + r + '<>"",M' + r + '<0.2),"LOW DISCRIMINATION — review item","OK"))))']);
    helper.push(['=IFERROR(VARP(' + preRng + '),0)']);
  });

  sh.getRange(FIRST_ROW, 1, rows.length, 14).setValues(rows)
    .setFontFamily('Arial').setFontSize(9).setHorizontalAlignment('center')
    .setBorder(true, true, true, true, true, true);
  sh.getRange(FIRST_ROW, 5, rows.length, 1).setHorizontalAlignment('left').setWrap(true);
  sh.getRange(FIRST_ROW, 14, rows.length, 1).setHorizontalAlignment('left').setWrap(true);
  sh.getRange(FIRST_ROW, 8, rows.length, 1).setNumberFormat('0.00');
  sh.getRange(FIRST_ROW, 9, rows.length, 1).setNumberFormat('0%');
  sh.getRange(FIRST_ROW, 10, rows.length, 1).setNumberFormat('0.00');
  sh.getRange(FIRST_ROW, 11, rows.length, 2).setNumberFormat('0%');
  sh.getRange(FIRST_ROW, 13, rows.length, 1).setNumberFormat('0.00');

  sh.getRange(HDR_ROW, 16).setValue('Item variance (helper)').setFontSize(8).setFontStyle('italic');
  sh.getRange(FIRST_ROW, 16, helper.length, 1).setFormulas(helper).setNumberFormat('0.000');
  sh.hideColumns(16);

  addRule_(sh, [sh.getRange(FIRST_ROW, 14, rows.length, 1)],
    '=LEFT($N' + FIRST_ROW + ',18)="LOW DISCRIMINATION"', COLORS.red, '#9C0006');

  var relRow = FIRST_ROW + N_ITEMS + 2;   // 49
  sectionBar_(sh, relRow, "Reliability (Cronbach's alpha)", 14);
  var lastItemRow = FIRST_ROW + N_ITEMS - 1;
  var alpha = [
    ['Number of items (k)', '=' + N_ITEMS, '0'],
    ['Sum of item variances', '=IFERROR(SUM($P$' + FIRST_ROW + ':$P$' + lastItemRow + '),"")', '0.000'],
    ['Variance of total scores', '=IFERROR(VARP(' + preTot + '),"")', '0.000'],
    ["Cronbach's alpha (pre-test)",
     '=IFERROR((' + N_ITEMS + '/(' + N_ITEMS + '-1))*(1-B' + (relRow + 2) + '/B' + (relRow + 3) + '),"")', '0.000']
  ];
  alpha.forEach(function (a, i) {
    var r = relRow + 1 + i;
    sh.getRange(r, 1).setValue(a[0]).setFontWeight(i === 3 ? 'bold' : 'normal').setFontFamily('Arial').setFontSize(10);
    sh.getRange(r, 2).setFormula(a[1]).setNumberFormat(a[2]).setHorizontalAlignment('center')
      .setFontWeight(i === 3 ? 'bold' : 'normal').setBorder(true, true, true, true, false, false);
  });
  sh.getRange(relRow + 6, 1, 2, 14).merge().setValue(
    'Expect alpha between 0.82 and 0.88 for a 41-item mixed-format instrument. Below 0.70, category-level reporting is not yet ' +
    'trustworthy for individual students — use it as a class signal only, and copy the computed alpha into Settings cell B16 so ' +
    'the growth statistics use your real value instead of the 0.85 default.')
    .setFontSize(9).setFontStyle('italic').setFontColor(COLORS.muted).setWrap(true).setVerticalAlignment('top');

  sh.setFrozenRows(HDR_ROW);
}

// ---- Intervention Groups --------------------------------------------------

function buildGroups_(ss) {
  var sh = sheetNamed_(ss, SHEETS.groups);
  sh.setHiddenGridlines(true);
  titleBar_(sh, 'Intervention Groups', 16, FREEZE_GROUPS);
  subtitle_(sh, 2, 'Group rosters build themselves from the Student Report and update as scores change. ' +
    'Green = Mastered (80%+), amber = Approaching (60–79%), red = Not Yet (below 60%).', 16, FREEZE_GROUPS);

  var REP = "'" + SHEETS.report + "'", S = SHEETS.settings;
  var NAMES = REP + '!$B$' + FIRST_ROW + ':$B$' + LAST_ROW;
  var WEAK = REP + '!$' + colA1(R_WEAK1) + '$' + FIRST_ROW + ':$' + colA1(R_WEAK1) + '$' + LAST_ROW;

  sectionBar_(sh, 4, 'Whole-class picture — how many students are "Not Yet" in each category?', 16, FREEZE_GROUPS);
  headerRow_(sh, 5, 1, ['Category', 'Not Yet', 'Approaching', 'Mastered', 'Recommendation']);
  [80, 75, 90, 75, 620].forEach(function (w, i) { sh.setColumnWidth(i + 1, w); });

  CATEGORIES.forEach(function (c, i) {
    var r = 6 + i;
    var oc = REP + '!$' + POST_CAT_COLS[i] + '$' + FIRST_ROW + ':$' + POST_CAT_COLS[i] + '$' + LAST_ROW;
    var pc = REP + '!$' + PRE_CAT_COLS[i] + '$' + FIRST_ROW + ':$' + PRE_CAT_COLS[i] + '$' + LAST_ROW;
    sh.getRange(r, 1, 1, 5).setValues([[
      c.code,
      '=COUNTIFS(' + oc + ',"<"&' + S + '!$B$12,' + oc + ',">=0")+COUNTIFS(' + oc + ',"",' + pc + ',"<"&' + S + '!$B$12,' + pc + ',">=0")',
      '=COUNTIFS(' + oc + ',">="&' + S + '!$B$12,' + oc + ',"<"&' + S + '!$B$11)+COUNTIFS(' + oc + ',"",' + pc + ',">="&' + S + '!$B$12,' + pc + ',"<"&' + S + '!$B$11)',
      '=COUNTIFS(' + oc + ',">="&' + S + '!$B$11)+COUNTIFS(' + oc + ',"",' + pc + ',">="&' + S + '!$B$11)',
      '=IFERROR(IF(B' + r + '+C' + r + '+D' + r + '=0,"",IF(B' + r + '/(B' + r + '+C' + r + '+D' + r + ')>=0.4,' +
        '"WHOLE CLASS: "&' + S + '!$E$' + (SET_CAT_FIRST + i) + ',' +
        'IF(B' + r + '=0,"Maintain through spiral review",' +
        '"SMALL GROUP ("&B' + r + '&" students): "&' + S + '!$E$' + (SET_CAT_FIRST + i) + '))),"")'
    ]]).setFontFamily('Arial').setFontSize(9).setBorder(true, true, true, true, true, true);
    sh.getRange(r, 1, 1, 4).setHorizontalAlignment('center');
    sh.getRange(r, 1).setFontWeight('bold');
    sh.getRange(r, 5).setWrap(true).setVerticalAlignment('top');
  });
  addRule_(sh, [sh.getRange(6, 5, CATEGORIES.length, 1)], '=LEFT($E6,11)="WHOLE CLASS"', COLORS.red, '#9C0006');

  sectionBar_(sh, 14, 'Group rosters — built automatically from each student’s weakest category', 16, FREEZE_GROUPS);
  headerRow_(sh, 15, 1, ['Group', 'n', 'Students']);
  CATEGORIES.forEach(function (c, i) {
    var r = 16 + i;
    sh.getRange(r, 1, 1, 3).setValues([[
      c.code,
      '=COUNTIF(' + WEAK + ',$A' + r + ')',
      '=IFERROR(IF(COUNTIF(' + WEAK + ',$A' + r + ')=0,"—",TEXTJOIN(", ",TRUE,FILTER(' + NAMES + ',' + WEAK + '=$A' + r + '))),"—")'
    ]]).setFontFamily('Arial').setFontSize(9).setBorder(true, true, true, true, true, true);
    sh.getRange(r, 1, 1, 2).setHorizontalAlignment('center');
    sh.getRange(r, 1).setFontWeight('bold');
    sh.getRange(r, 3).setWrap(true).setVerticalAlignment('top');
  });
  noteBand_(sh, 23, 16,
    'Do not run more than three groups at once. A student appears in the group for their WEAKEST category; ' +
    'the student table below shows the full profile, including a second group if you have capacity.',
    FREEZE_GROUPS);

  sectionBar_(sh, 25, 'Student-level mastery heat map', 16, FREEZE_GROUPS);
  var codes = CATEGORIES.map(function (c) { return c.code; });
  headerRow_(sh, 26, 1, ['Student ID', 'Student Name', 'Period', 'Post total', 'Achievement level',
                         'PRIMARY GROUP', 'Secondary group', 'Not Yet count'].concat(codes));

  var first = 27, block = [];
  for (var k = 0; k < N_STUDENTS; k++) {
    var r = first + k, sr = FIRST_ROW + k, row = [];
    row.push('=' + REP + '!$A' + sr, '=' + REP + '!$B' + sr, '=' + REP + '!$C' + sr,
             '=' + REP + '!$G' + sr, '=' + REP + '!$I' + sr,
             '=' + REP + '!$' + colA1(R_WEAK1) + sr, '=' + REP + '!$' + colA1(R_WEAK2) + sr,
             '=IF($B' + r + '="","",COUNTIF(I' + r + ':O' + r + ',"Not Yet"))');
    for (var i = 0; i < 7; i++) {
      var oc = REP + '!$' + POST_CAT_COLS[i] + sr, pc = REP + '!$' + PRE_CAT_COLS[i] + sr;
      row.push('=IFERROR(IF(' + oc + '<>"",IF(' + oc + '>=' + SHEETS.settings + '!$B$11,"Mastered",' +
        'IF(' + oc + '>=' + SHEETS.settings + '!$B$12,"Approaching","Not Yet")),' +
        'IF(' + pc + '<>"",IF(' + pc + '>=' + SHEETS.settings + '!$B$11,"Mastered",' +
        'IF(' + pc + '>=' + SHEETS.settings + '!$B$12,"Approaching","Not Yet")),"")),"")');
    }
    block.push(row);
  }
  sh.getRange(first, 1, N_STUDENTS, 15).setFormulas(block)
    .setFontFamily('Arial').setFontSize(9).setHorizontalAlignment('center')
    .setBorder(true, true, true, true, true, true);
  sh.getRange(first, 6, N_STUDENTS, 1).setFontWeight('bold');
  [85, 155, 60, 75, 135, 100, 95, 75].forEach(function (w, i) { sh.setColumnWidth(i + 1, w); });
  for (var c2 = 9; c2 <= 15; c2++) sh.setColumnWidth(c2, 85);

  var heat = sh.getRange(first, 9, N_STUDENTS, 7);
  addRule_(sh, [heat], '=I' + first + '="Mastered"', COLORS.green);
  addRule_(sh, [heat], '=I' + first + '="Approaching"', COLORS.amber);
  addRule_(sh, [heat], '=I' + first + '="Not Yet"', COLORS.red);
  addRule_(sh, [sh.getRange(first, 8, N_STUDENTS, 1)], '=AND(ISNUMBER($H' + first + '),$H' + first + '>=4)',
    COLORS.red, '#9C0006');

  sh.setFrozenRows(26);
  sh.setFrozenColumns(FREEZE_GROUPS);
}

// ---- Standards Coverage ---------------------------------------------------

function buildCoverage_(ss) {
  var sh = sheetNamed_(ss, SHEETS.coverage);
  sh.setHiddenGridlines(true);
  titleBar_(sh, 'Standards Coverage — what this instrument measures, and what it does not', 4);
  subtitle_(sh, 2, 'Read the second table before planning from this data. Roughly a quarter of the Grade 7 expectations cannot be ' +
    'measured in a written booklet and must be assessed through classroom performance tasks.', 4);
  [110, 470, 130, 90].forEach(function (w, i) { sh.setColumnWidth(i + 1, w); });

  var assessed = [
    ['7.L.GC.1', 'Grammar, usage & mechanics (semicolons in a complex series)', '35', 'C-LNG'],
    ['7.L.GC.2.a', 'Apply syntax understanding to comprehend and analyze texts', '21', 'I-LNG'],
    ['7.L.GC.2.b', 'Sentence variety; consistent verb tense', '32, essay T3', 'C-LNG'],
    ['7.L.GC.2.c', 'Distinguish active and passive voice; revise for active voice', '33, essay T3', 'C-LNG'],
    ['7.L.GC.2.d', 'Avoid misplaced and dangling modifiers', '34, essay T3', 'C-LNG'],
    ['7.L.V.2.a', 'Greek and Latin roots and affixes', '14', 'I-LNG'],
    ['7.L.V.2.b', 'Parts of speech as a clue to meaning', '15', 'I-LNG'],
    ['7.L.V.2.d', 'Use parts of speech to choose precise words when writing', '36', 'C-LNG'],
    ['7.L.V.3.b', 'Word relationships and context clues beyond the sentence', '3', 'I-LNG'],
    ['7.L.V.3.c', 'Connotations of words sharing a denotation', '19', 'I-LNG'],
    ['7.L.V.1.b', 'Use grade-level academic vocabulary to communicate precisely', 'essay T3', 'C-LNG'],
    ['7.T.C.1.a', 'Multiple purposes within a text and the audiences they target', '16', 'I-CSS'],
    ['7.T.C.1.c', 'Construct texts for a specific purpose and audience', 'essay T1', 'C-CSS'],
    ['7.T.C.2.a', 'Determine the prevailing perspective in a text', '20A', 'I-CSS'],
    ['7.T.C.2.b', 'How evidence and tone reveal perspective and affect credibility', '20B', 'I-CSS'],
    ['7.T.C.2.d', 'Use credible sources to research answers to questions', 'essay T2', 'C-TEC'],
    ['7.T.SS.1.a', 'How authors modify organizational structures to achieve purposes', '11', 'I-CSS'],
    ['7.T.SS.1.b', 'Design texts employing structures and features', 'essay T1', 'C-CSS'],
    ['7.T.SS.1.c', 'Varied transitions connecting ideas, sentences, and paragraphs', '30, essay T1', 'C-CSS'],
    ['7.T.SS.1.d', 'Multi-paragraph texts: introduction, support, conclusion', '25, 38, essay T1', 'C-CSS'],
    ['7.T.SS.2.a', 'How figurative and connotative language shape meaning, mood, tone', '4', 'I-CSS'],
    ['7.T.SS.2.c', 'Situational use of formal or informal style', '31, essay T1', 'C-CSS'],
    ['7.T.T.1.a', 'Narrative techniques developing plot, character, setting', '1', 'I-TEC'],
    ['7.T.T.1.b', 'Plot structure, conflict, and narrative devices', '2', 'I-TEC'],
    ['7.T.T.1.c', 'How themes are developed and expressed across texts', '5, 8', 'I-TEC'],
    ['7.T.T.1.d', 'Compare a fictional portrayal with an account of the same material', '10', 'I-PRA'],
    ['7.T.T.2.a', 'Expository techniques: main ideas, facts, statistics, text features', '12, 13', 'I-TEC'],
    ['7.T.T.2.b', 'How two authors on one topic emphasize different evidence', '22', 'I-TEC'],
    ['7.T.T.2.d', 'Apply expository techniques; elaborate on reasons', '28, essay T2', 'C-TEC'],
    ['7.T.T.3.a', 'Argumentative techniques: claim, evidence, counterclaim, conclusion', '17, 18', 'I-TEC'],
    ['7.T.T.3.c', 'Apply argumentative techniques when writing', '26, 27, 29, essay T2', 'C-TEC'],
    ['7.T.T.4.a', 'Poetic techniques: stanzas, rhyme, imagery, sound devices', '6, 7', 'I-TEC'],
    ['7.T.PM.1.a', 'Analyze a myth a modern writer adapted; features of style and theme', '9, 10', 'I-PRA'],
    ['7.T.RA.2.a', 'Locate evidence; record standard bibliographic information', '24', 'I-PRA'],
    ['7.T.RA.2.b', 'Analyze sources for credibility and relevance', '23', 'I-PRA'],
    ['7.T.RA.2.c', 'Follow a standard citation format when integrating evidence', '27, 37, essay T2', 'C-TEC']
  ];
  sectionBar_(sh, 4, 'Expectations assessed by this instrument', 4);
  headerRow_(sh, 5, 1, ['Expectation', 'Skill', 'Items', 'Category']);
  sh.getRange(6, 1, assessed.length, 4).setValues(assessed)
    .setFontFamily('Arial').setFontSize(9).setBorder(true, true, true, true, true, true);
  sh.getRange(6, 2, assessed.length, 1).setWrap(true);
  sh.getRange(6, 1, assessed.length, 1).setHorizontalAlignment('center');
  sh.getRange(6, 3, assessed.length, 2).setHorizontalAlignment('center');

  var gapRow = 6 + assessed.length + 2;
  var gaps = [
    ['7.T.C.1.b', 'Use text mode features across disciplinary texts',
     'Partially covered by item 13 (data table). Full coverage needs multimodal and digital texts — assess in a science or social studies reading task.'],
    ['7.T.SS.2.b', 'Use figurative language for intentional effect when writing',
     'Narrative or poetic writing task. The essay on this instrument is argumentative.'],
    ['7.T.T.1.e', 'Apply narrative techniques to enhance writing', 'Narrative writing performance task.'],
    ['7.T.T.4.b', 'Apply poetic techniques to produce poetry', 'Poetry writing performance task.'],
    ['7.T.RA.1.a-c', 'Generate research questions; conduct research; analyze from research',
     'Multi-day research unit with a process rubric — cannot be captured in a single sitting.'],
    ['7.T.PM.1.b', 'Analyze a genre of literature from a particular time period',
     'Extended text study with a culminating analysis.'],
    ['7.L.V.1.a', 'Acquire vocabulary through print, digital, and multimodal texts',
     'Ongoing vocabulary assessment across the year.'],
    ['7.L.V.3.d / e', 'Use print and digital reference tools to clarify meaning',
     'Requires tool access, which conflicts with secure testing. Assess during writing conferences.'],
    ['7.L.V.2.c', 'Construct words from Greek and Latin roots and affixes',
     'Assessed only indirectly through essay word choice. Use a morphology quiz.'],
    ['K-12.P.CP.1', 'Collaboration', 'Structured discussion protocol with an observation rubric.'],
    ['K-12.P.CP.2', 'Presentation', 'Oral presentation with a presentation rubric.']
  ];
  sectionBar_(sh, gapRow, 'Expectations NOT assessed — and how to assess them instead', 4);
  headerRow_(sh, gapRow + 1, 1, ['Expectation', 'Skill', 'How to assess it instead']);
  sh.getRange(gapRow + 2, 1, gaps.length, 3).setValues(gaps)
    .setFontFamily('Arial').setFontSize(9).setBorder(true, true, true, true, true, true);
  sh.getRange(gapRow + 2, 2, gaps.length, 2).setWrap(true).setVerticalAlignment('top');
  sh.getRange(gapRow + 2, 1, gaps.length, 1).setHorizontalAlignment('center');
  sh.setColumnWidth(3, 470);
}

// ======================================================================
// ===  Scoring.gs
// ======================================================================

/**
 * Scoring.gs — auto-scoring engine.
 *
 * Implements the exact partial-credit rules from the answer keys:
 *
 *   Selected response      1 if the key matches, else 0
 *   Two-part / EBSR        1 point per correct part  ->  2 / 1 / 0
 *   Select TWO             2 = both correct, no incorrect
 *                          1 = exactly one correct AND no more than one incorrect
 *                          0 = anything else, INCLUDING three or more selections
 *   Match (4 cells)        2 = all four, 1 = exactly three, 0 = two or fewer
 *
 * The essay is never auto-scored. A rubric score is a professional judgment and
 * the three trait columns stay under the teacher's hand.
 */

var PROP_FORM_A = 'formIdA';
var PROP_FORM_B = 'formIdB';

/** Canonical question titles. The Form builder and the scorer both call this,
 *  so they cannot drift apart. */
function questionTitle_(item, part) {
  var n = item.n;
  switch (item.type) {
    case 'SR':    return 'Item ' + n;
    case 'MP':    return 'Item ' + n + ' — Part ' + part;          // 'A' | 'B'
    case 'MS':    return 'Item ' + n + ' — select TWO';
    case 'MATCH': return 'Item ' + n + ' — row ' + part;           // 'a'..'d'
  }
  return 'Item ' + n;
}

/** Score one item. `resp` is a string, or an array for MS/MP/MATCH. */
function scoreItem_(item, key, resp) {
  if (resp === null || resp === undefined) return null;

  if (item.type === 'SR') {
    if (resp === '') return null;
    return resp === key ? 1 : 0;
  }

  if (item.type === 'MP') {
    if ((resp[0] === '' || resp[0] == null) && (resp[1] === '' || resp[1] == null)) return null;
    var pts = 0;
    if (resp[0] === key[0]) pts++;
    if (resp[1] === key[1]) pts++;
    return pts;
  }

  if (item.type === 'MS') {
    var sel = (resp || []).filter(function (x) { return x !== '' && x != null; });
    if (!sel.length) return null;
    if (sel.length >= 3) return 0;                    // over-selection scores zero
    var correct = 0, incorrect = 0;
    sel.forEach(function (s) { key.indexOf(s) >= 0 ? correct++ : incorrect++; });
    if (correct === 2 && incorrect === 0) return 2;
    if (correct === 1 && incorrect <= 1) return 1;
    return 0;
  }

  if (item.type === 'MATCH') {
    var given = resp || [];
    var any = given.some(function (x) { return x !== '' && x != null; });
    if (!any) return null;
    var hits = 0;
    for (var i = 0; i < 4; i++) if (given[i] === key[i]) hits++;
    if (hits === 4) return 2;
    if (hits === 3) return 1;
    return 0;
  }

  return null;
}

/**
 * Read every response from the stored Form for `formLabel` ('A' or 'B'),
 * score it, and write the item points into the matching entry sheet row.
 * Matching is by Student ID against the Roster.
 */
function scoreFormResponses_(formLabel) {
  var props = PropertiesService.getDocumentProperties();
  var formId = props.getProperty(formLabel === 'A' ? PROP_FORM_A : PROP_FORM_B);
  if (!formId) {
    return {scored: 0, unmatched: [], error:
      'No Form ' + formLabel + ' has been created yet. Use ELA Reporting ▸ Create answer-sheet Form.'};
  }

  var form;
  try { form = FormApp.openById(formId); }
  catch (e) { return {scored: 0, unmatched: [], error: 'Could not open the Form: ' + e.message}; }

  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var entry = ss.getSheetByName(formLabel === 'A' ? SHEETS.pre : SHEETS.post);
  var roster = ss.getSheetByName(SHEETS.roster);
  if (!entry || !roster) return {scored: 0, unmatched: [], error: 'Run "Set up workbook" first.'};

  // Student ID -> sheet row
  var ids = roster.getRange(FIRST_ROW, 1, N_STUDENTS, 1).getValues();
  var rowOf = {};
  ids.forEach(function (v, i) {
    var id = String(v[0]).trim();
    if (id) rowOf[id] = FIRST_ROW + i;
  });

  var key = KEYS[formLabel];
  var responses = form.getResponses();
  var scored = 0, unmatched = [];

  responses.forEach(function (fr) {
    var byTitle = {};
    fr.getItemResponses().forEach(function (ir) {
      byTitle[ir.getItem().getTitle()] = ir.getResponse();
    });

    var sid = String(byTitle['Student ID'] || '').trim();
    var row = rowOf[sid];
    if (!row) { if (sid) unmatched.push(sid); return; }

    var points = [];
    SCORED_ITEMS.forEach(function (it) {
      var resp;
      if (it.type === 'SR')        resp = byTitle[questionTitle_(it)] || '';
      else if (it.type === 'MP')   resp = [byTitle[questionTitle_(it, 'A')] || '', byTitle[questionTitle_(it, 'B')] || ''];
      else if (it.type === 'MS')   resp = byTitle[questionTitle_(it)] || [];
      else if (it.type === 'MATCH') resp = ['a', 'b', 'c', 'd'].map(function (p) { return byTitle[questionTitle_(it, p)] || ''; });
      points.push(scoreItem_(it, key[it.n], resp));
    });

    // Write items 1-38 only; the three essay trait columns stay untouched.
    entry.getRange(row, FIRST_ITEM_COL, 1, points.length)
         .setValues([points.map(function (p) { return p === null ? '' : p; })]);
    scored++;
  });

  return {scored: scored, unmatched: unmatched, total: responses.length};
}

/** Menu action: score both forms and report what happened. */
function scoreAllForms() {
  var ui = SpreadsheetApp.getUi();
  var out = [];
  ['A', 'B'].forEach(function (lbl) {
    var r = scoreFormResponses_(lbl);
    if (r.error) { out.push('Form ' + lbl + ': ' + r.error); return; }
    var line = 'Form ' + lbl + ': scored ' + r.scored + ' of ' + r.total + ' responses.';
    if (r.unmatched.length) {
      line += '\n   Unmatched Student IDs (not on the Roster): ' +
              r.unmatched.slice(0, 12).join(', ') + (r.unmatched.length > 12 ? ' …' : '');
    }
    out.push(line);
  });
  out.push('\nReminder: essay trait scores (Q39_T1 / T2 / T3) are entered by hand.');
  ui.alert('Auto-scoring complete', out.join('\n\n'), ui.ButtonSet.OK);
}

/** Installable trigger target — scores a single submission as it arrives. */
function onFormSubmitHandler(e) {
  try {
    var props = PropertiesService.getDocumentProperties();
    var srcId = e && e.source && e.source.getId ? e.source.getId() : null;
    if (srcId === props.getProperty(PROP_FORM_A)) scoreFormResponses_('A');
    else if (srcId === props.getProperty(PROP_FORM_B)) scoreFormResponses_('B');
    else { scoreFormResponses_('A'); scoreFormResponses_('B'); }
  } catch (err) {
    console.error('onFormSubmitHandler: ' + err.message);
  }
}

/**
 * Self-test for the partial-credit rules. Run from the editor and check the log.
 * These assertions encode the scoring table in the answer keys.
 */
function testScoringRules() {
  var results = [], pass = 0, fail = 0;
  function t(label, got, want) {
    var ok = JSON.stringify(got) === JSON.stringify(want);
    ok ? pass++ : fail++;
    results.push((ok ? 'PASS  ' : 'FAIL  ') + label + '  got=' + JSON.stringify(got) + ' want=' + JSON.stringify(want));
  }
  var SR = {n: 1, type: 'SR'}, MP = {n: 2, type: 'MP'}, MS = {n: 8, type: 'MS'}, MT = {n: 22, type: 'MATCH'};

  t('SR correct',        scoreItem_(SR, 'B', 'B'), 1);
  t('SR incorrect',      scoreItem_(SR, 'B', 'A'), 0);
  t('SR blank',          scoreItem_(SR, 'B', ''), null);

  t('MP both',           scoreItem_(MP, ['B', 'C'], ['B', 'C']), 2);
  t('MP part A only',    scoreItem_(MP, ['B', 'C'], ['B', 'D']), 1);
  t('MP part B only',    scoreItem_(MP, ['B', 'C'], ['A', 'C']), 1);
  t('MP neither',        scoreItem_(MP, ['B', 'C'], ['A', 'D']), 0);
  t('MP blank',          scoreItem_(MP, ['B', 'C'], ['', '']), null);

  t('MS both correct',   scoreItem_(MS, ['A', 'C'], ['A', 'C']), 2);
  t('MS one correct only',        scoreItem_(MS, ['A', 'C'], ['A']), 1);
  t('MS one right one wrong',     scoreItem_(MS, ['A', 'C'], ['A', 'B']), 1);
  t('MS two wrong',               scoreItem_(MS, ['A', 'C'], ['B', 'D']), 0);
  t('MS three selected -> 0',     scoreItem_(MS, ['A', 'C'], ['A', 'C', 'B']), 0);
  t('MS four selected -> 0',      scoreItem_(MS, ['A', 'C'], ['A', 'B', 'C', 'D']), 0);
  t('MS blank',                   scoreItem_(MS, ['A', 'C'], []), null);

  var K = ['S1', 'S2', 'B', 'B'];
  t('MATCH all four',    scoreItem_(MT, K, ['S1', 'S2', 'B', 'B']), 2);
  t('MATCH three',       scoreItem_(MT, K, ['S1', 'S2', 'B', 'S1']), 1);
  t('MATCH two',         scoreItem_(MT, K, ['S1', 'S2', 'S1', 'S1']), 0);
  t('MATCH blank',       scoreItem_(MT, K, ['', '', '', '']), null);

  // Blueprint integrity: category point totals must match the state blueprint.
  var totals = {};
  ITEMS.forEach(function (it) { totals[it.cat] = (totals[it.cat] || 0) + it.max; });
  CATEGORIES.forEach(function (c) { t('category ' + c.code + ' points', totals[c.code], c.max); });
  var grand = ITEMS.reduce(function (s, it) { return s + it.max; }, 0);
  t('total points', grand, 60);
  t('item columns', ITEMS.length, 41);

  // Every scored item must have a key on both forms.
  ['A', 'B'].forEach(function (f) {
    var missing = SCORED_ITEMS.filter(function (it) { return KEYS[f][it.n] === undefined; })
                              .map(function (it) { return it.n; });
    t('Form ' + f + ' keys complete', missing, []);
  });
  // Key shapes must match item types.
  ['A', 'B'].forEach(function (f) {
    var bad = SCORED_ITEMS.filter(function (it) {
      var k = KEYS[f][it.n];
      if (it.type === 'SR') return typeof k !== 'string';
      if (it.type === 'MP' || it.type === 'MS') return !(k instanceof Array) || k.length !== 2;
      if (it.type === 'MATCH') return !(k instanceof Array) || k.length !== 4;
      return false;
    }).map(function (it) { return it.n; });
    t('Form ' + f + ' key shapes', bad, []);
  });
  // No item may share a key letter across forms (form-security check).
  var shared = SCORED_ITEMS.filter(function (it) {
    return it.type === 'SR' && KEYS.A[it.n] === KEYS.B[it.n];
  }).map(function (it) { return it.n; });
  t('no shared SR keys across forms', shared, []);

  Logger.log(results.join('\n'));
  Logger.log('\n' + pass + ' passed, ' + fail + ' failed.');
  return {pass: pass, fail: fail, results: results};
}

// ======================================================================
// ===  FormBuilder.gs
// ======================================================================

/**
 * FormBuilder.gs — generates a Google Form answer sheet for Form A or Form B.
 *
 * Design decision worth knowing: the Form does NOT contain the passages.
 * Students read the printed or PDF booklet and use the Form the way they would
 * use a bubble sheet. Two reasons:
 *
 *   1. Scrolling 1,500 words of passage inside a Google Form, then scrolling
 *      back and forth to each item, is a genuinely worse reading experience
 *      than a booklet — and it would depress reading scores for reasons that
 *      have nothing to do with reading ability.
 *   2. Keeping passages out of the Form keeps the item content out of a
 *      student-accessible document, which matters because Form A must stay
 *      secure until Form B has been administered.
 *
 * The Form collects raw responses only. All scoring happens in Scoring.gs, so
 * the partial-credit rules match the paper answer keys exactly. (Google Forms'
 * built-in quiz grading is all-or-nothing on checkbox items, which would score
 * every "select TWO" item wrong for a student who got one of the two right.)
 */

function createFormA() { createAnswerSheetForm_('A'); }
function createFormB() { createAnswerSheetForm_('B'); }

function createAnswerSheetForm_(formLabel) {
  var ui = SpreadsheetApp.getUi();
  var props = PropertiesService.getDocumentProperties();
  var prop = formLabel === 'A' ? PROP_FORM_A : PROP_FORM_B;

  if (props.getProperty(prop)) {
    var again = ui.alert('Form ' + formLabel + ' already exists',
      'A Form ' + formLabel + ' answer sheet has already been created for this spreadsheet.\n\n' +
      'Create a NEW one? The old Form and its responses will be left untouched, but this ' +
      'spreadsheet will stop scoring from it.', ui.ButtonSet.YES_NO);
    if (again !== ui.Button.YES) return;
  }

  var testName = formLabel === 'A' ? 'Pre-Test' : 'Post-Test';
  var form = FormApp.create('Grade 7 ELA — Form ' + formLabel + ' (' + testName + ') Answer Sheet');
  form.setDescription(
    'Record your answers here. Read the passages and the full answer choices in your test booklet.\n\n' +
    '• Items worth 2 points have a Part A and a Part B, or ask you to select TWO answers.\n' +
    '• Answer every item. A blank earns nothing; a good guess sometimes earns a point.\n' +
    '• Your essay is written on paper and is not part of this form.');
  form.setProgressBar(true);
  form.setAllowResponseEdits(false);
  form.setShuffleQuestions(false);

  var id = form.addTextItem().setTitle('Student ID').setRequired(true);
  id.setHelpText('Type your Student ID exactly as it appears on your booklet. Scoring matches on this.');

  var LETTERS = ['A', 'B', 'C', 'D', 'E'];
  var partCounts = {1: 10, 2: 24, 3: 38};   // last item number in each part
  var partTitles = {
    1: 'Part 1 — Literary and Poetic Texts (items 1–10)',
    2: 'Part 2 — Paired Informational Texts (items 11–24)',
    3: 'Part 3 — Peer Revision Task (items 25–38)'
  };
  var currentPart = 0;

  SCORED_ITEMS.forEach(function (it) {
    var part = it.n <= partCounts[1] ? 1 : (it.n <= partCounts[2] ? 2 : 3);
    if (part !== currentPart) {
      currentPart = part;
      form.addPageBreakItem().setTitle(partTitles[part]);
    }

    var opts = LETTERS.slice(0, it.opts);

    if (it.type === 'SR') {
      form.addMultipleChoiceItem()
        .setTitle(questionTitle_(it))
        .setChoiceValues(opts)
        .setRequired(false);

    } else if (it.type === 'MP') {
      ['A', 'B'].forEach(function (p) {
        form.addMultipleChoiceItem()
          .setTitle(questionTitle_(it, p))
          .setChoiceValues(opts)
          .setRequired(false);
      });

    } else if (it.type === 'MS') {
      form.addCheckboxItem()
        .setTitle(questionTitle_(it))
        .setHelpText('Select exactly TWO. Selecting three or more scores zero.')
        .setChoiceValues(opts)
        .setRequired(false);

    } else if (it.type === 'MATCH') {
      var help = 'Write S1 (Source 1 only), S2 (Source 2 only), or B (both sources) for each statement.';
      ['a', 'b', 'c', 'd'].forEach(function (p, i) {
        var mc = form.addMultipleChoiceItem()
          .setTitle(questionTitle_(it, p))
          .setChoiceValues(['S1', 'S2', 'B'])
          .setRequired(false);
        if (i === 0) mc.setHelpText(help);
      });
    }
  });

  form.addPageBreakItem().setTitle('Part 4 — Extended Writing Task');
  form.addSectionHeaderItem()
    .setTitle('Write your essay on paper')
    .setHelpText('Your essay is scored on the three-trait rubric by your teacher and is not submitted here. ' +
                 'Make sure your name is on your lined pages.');

  props.setProperty(prop, form.getId());
  installFormTrigger_();

  var msg = 'Created: ' + form.getTitle() +
    '\n\nShare this link with students:\n' + form.getPublishedUrl() +
    '\n\nEdit the Form here:\n' + form.getEditUrl() +
    '\n\nResponses will score automatically on submit. You can also run ' +
    'ELA Reporting ▸ Score Form responses now at any time.' +
    '\n\nStudents still need the printed booklet — this Form holds no passages or answer choices.';
  ui.alert('Form ' + formLabel + ' answer sheet created', msg, ui.ButtonSet.OK);
}

/** Install the on-submit trigger once. */
function installFormTrigger_() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var exists = ScriptApp.getProjectTriggers().some(function (t) {
    return t.getHandlerFunction() === 'onFormSubmitHandler';
  });
  if (exists) return;
  ScriptApp.newTrigger('onFormSubmitHandler').forSpreadsheet(ss).onFormSubmit().create();
}

/** Show the links for whichever Forms exist. */
function showFormLinks() {
  var props = PropertiesService.getDocumentProperties();
  var lines = [];
  [['A', PROP_FORM_A], ['B', PROP_FORM_B]].forEach(function (pair) {
    var fid = props.getProperty(pair[1]);
    if (!fid) { lines.push('Form ' + pair[0] + ': not created yet.'); return; }
    try {
      var f = FormApp.openById(fid);
      lines.push('Form ' + pair[0] + ' — ' + f.getTitle() +
        '\n  Student link: ' + f.getPublishedUrl() +
        '\n  Edit link:    ' + f.getEditUrl() +
        '\n  Responses:    ' + f.getResponses().length);
    } catch (e) {
      lines.push('Form ' + pair[0] + ': could not be opened (' + e.message + ')');
    }
  });
  SpreadsheetApp.getUi().alert('Answer-sheet Forms', lines.join('\n\n'), SpreadsheetApp.getUi().ButtonSet.OK);
}

// ======================================================================
// ===  Reports.gs
// ======================================================================

/**
 * Reports.gs — printable one-page profiles, one per student.
 *
 * Builds a single Google Doc with a page break between students, so a teacher
 * can print once and hand out. Each page carries the student's totals, the
 * seven category results with mastery flags, growth statistics, and the two
 * areas to work on next — written in language a student or a caregiver can read
 * without a measurement glossary.
 *
 * Deliberately NOT included: emailing reports to families. That depends on
 * guardian-contact data this workbook does not hold and on district policy about
 * what may be sent outside the domain. Print or share the Doc instead.
 */

function generateStudentReports() {
  var ui = SpreadsheetApp.getUi();
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var rep = ss.getSheetByName(SHEETS.report);
  if (!rep) { ui.alert('Run "Set up workbook" first.'); return; }

  var periodResp = ui.prompt('Student reports',
    'Class period to print (leave blank for all students):', ui.ButtonSet.OK_CANCEL);
  if (periodResp.getSelectedButton() !== ui.Button.OK) return;
  var wantPeriod = periodResp.getResponseText().trim();

  var data = rep.getRange(FIRST_ROW, 1, N_STUDENTS, R_FOCUS).getDisplayValues();
  var codes = CATEGORIES.map(function (c) { return c.code; });

  var rows = data.filter(function (r) {
    if (!r[R_NAME - 1]) return false;
    if (!r[R_PRE_T - 1] && !r[R_POST_T - 1]) return false;
    if (wantPeriod && String(r[R_PER - 1]).trim() !== wantPeriod) return false;
    return true;
  });
  if (!rows.length) { ui.alert('No students matched.', 'Check the period name and that scores are entered.', ui.ButtonSet.OK); return; }

  var stamp = Utilities.formatDate(new Date(), Session.getScriptTimeZone(), 'yyyy-MM-dd');
  var doc = DocumentApp.create('Grade 7 ELA — Student Reports' +
    (wantPeriod ? ' (' + wantPeriod + ')' : '') + ' — ' + stamp);
  var body = doc.getBody();
  body.setMarginTop(48).setMarginBottom(48).setMarginLeft(54).setMarginRight(54);

  rows.forEach(function (r, idx) {
    if (idx > 0) body.appendPageBreak();
    writeOneReport_(body, r, codes);
  });

  doc.saveAndClose();
  ui.alert('Student reports created',
    rows.length + ' report' + (rows.length === 1 ? '' : 's') + ' written to:\n\n' +
    doc.getName() + '\n\n' + doc.getUrl(), ui.ButtonSet.OK);
}

function writeOneReport_(body, r, codes) {
  var name = r[R_NAME - 1];
  var period = r[R_PER - 1];
  var preT = r[R_PRE_T - 1], postT = r[R_POST_T - 1];
  var preL = r[R_PRE_L - 1], postL = r[R_POST_L - 1];
  var gain = r[R_GAIN - 1], reliable = r[R_REL - 1], metTarget = r[R_TGT - 1];
  var weak1 = r[R_WEAK1 - 1], weak2 = r[R_WEAK2 - 1];
  var near = r[R_NEAR - 1], essayFlag = r[R_ESSAY - 1];
  var focus = r[R_FOCUS - 1];

  var h = body.appendParagraph(name);
  h.setHeading(DocumentApp.ParagraphHeading.HEADING1);
  var sub = body.appendParagraph('Grade 7 English Language Arts   ·   Period ' + period +
    '   ·   ' + Utilities.formatDate(new Date(), Session.getScriptTimeZone(), 'MMMM d, yyyy'));
  sub.setForegroundColor('#5B6470').setFontSize(9);

  // ---- overall -----------------------------------------------------------
  body.appendParagraph('Overall').setHeading(DocumentApp.ParagraphHeading.HEADING2);
  var overall = [['', 'Score (of 60)', 'Achievement level']];
  if (preT !== '') overall.push(['Beginning of year', preT, preL]);
  if (postT !== '') overall.push(['End of year', postT, postL]);
  styleTable_(body.appendTable(overall));

  if (near === 'NEAR CUT') {
    var n = body.appendParagraph(
      'Note: this score sits within one standard error of a level boundary. The level label is not a reliable ' +
      'description on its own — read the category results below alongside classroom work.');
    n.setFontSize(9).setItalic(true).setForegroundColor('#7F6000');
  }

  // ---- growth ------------------------------------------------------------
  if (preT !== '' && postT !== '') {
    body.appendParagraph('Growth').setHeading(DocumentApp.ParagraphHeading.HEADING2);
    var g = Number(gain);
    var sentence;
    if (reliable === 'Yes' && g > 0) {
      sentence = 'Gained ' + g + ' points from beginning to end of year. This gain is large enough to be ' +
                 'statistically reliable for one student — it is real growth, not measurement noise.';
    } else if (g > 0) {
      sentence = 'Gained ' + g + ' points from beginning to end of year. This is movement in the right ' +
                 'direction, but it is small enough that it may partly reflect measurement error rather than ' +
                 'growth alone.';
    } else if (g === 0) {
      sentence = 'Scored the same at the beginning and end of year.';
    } else {
      sentence = 'Scored ' + Math.abs(g) + ' points lower at the end of year. Before drawing a conclusion, ' +
                 'check testing conditions and effort on the second administration.';
    }
    body.appendParagraph(sentence).setFontSize(10);
    body.appendParagraph('Growth target met: ' + (metTarget || '—')).setFontSize(9)
      .setForegroundColor('#5B6470');
  }

  // ---- category profile --------------------------------------------------
  body.appendParagraph('What the results show, skill by skill')
    .setHeading(DocumentApp.ParagraphHeading.HEADING2);

  var tbl = [['Skill area', 'Beginning', 'End', 'Where this stands']];
  codes.forEach(function (code, i) {
    var pre = r[R_PRECAT - 1 + i];
    var post = r[R_POSTCAT - 1 + i];
    var latest = post !== '' ? post : pre;
    tbl.push([CATEGORIES[i].name.replace(/^(Interpreting|Constructing) — /, ''),
              pre || '—', post || '—', masteryWord_(latest)]);
  });
  styleTable_(body.appendTable(tbl));
  body.appendParagraph(
    'Reading (Interpreting) skills are listed first, writing (Constructing) skills second. ' +
    'Each area is worth between 6 and 16 points, so a single percentage here is a starting point for a ' +
    'conversation, not a final verdict.').setFontSize(8.5).setItalic(true).setForegroundColor('#5B6470');

  // ---- next steps --------------------------------------------------------
  body.appendParagraph('What we are working on next').setHeading(DocumentApp.ParagraphHeading.HEADING2);
  if (weak1) {
    var c1 = catByCode_(weak1);
    body.appendParagraph('Priority: ' + (c1 ? c1.name : weak1)).setFontSize(10).setBold(true);
    body.appendParagraph(focus || (c1 ? c1.focus : '')).setFontSize(10);
    if (weak2) {
      var c2 = catByCode_(weak2);
      body.appendParagraph('Also building: ' + (c2 ? c2.name : weak2)).setFontSize(9)
        .setForegroundColor('#5B6470');
    }
  }
  if (essayFlag) {
    body.appendParagraph(essayFlag + ' — the writing task could not be scored with the rubric, so the ' +
      'writing areas above are based on the other items only.')
      .setFontSize(9).setItalic(true).setForegroundColor('#7F6000');
  }

  body.appendParagraph(
    'About this assessment: a classroom pre/post measure built to the Georgia Milestones Grade 7 ELA blueprint. ' +
    'Achievement levels here are set by teacher content review, not by a state standard-setting panel, and are ' +
    'used to plan instruction — they do not predict a Georgia Milestones score.')
    .setFontSize(8).setItalic(true).setForegroundColor('#5B6470');
}

function masteryWord_(pctText) {
  if (!pctText) return '—';
  var v = parseFloat(String(pctText).replace('%', ''));
  if (isNaN(v)) return '—';
  if (v >= 80) return 'Strength — keep it sharp';
  if (v >= 60) return 'Almost there — small-group work';
  return 'Priority for reteaching';
}

function catByCode_(code) {
  for (var i = 0; i < CATEGORIES.length; i++) if (CATEGORIES[i].code === code) return CATEGORIES[i];
  return null;
}

function styleTable_(table) {
  table.setBorderColor('#C3C9D2');
  var head = table.getRow(0);
  for (var c = 0; c < head.getNumCells(); c++) {
    head.getCell(c).setBackgroundColor('#DCE6F1');
    head.getCell(c).editAsText().setBold(true).setFontSize(9);
  }
  for (var r = 1; r < table.getNumRows(); r++) {
    var row = table.getRow(r);
    for (var c2 = 0; c2 < row.getNumCells(); c2++) {
      row.getCell(c2).editAsText().setFontSize(9.5);
    }
  }
}

// ======================================================================
// ===  Menu.gs
// ======================================================================

/**
 * Menu.gs — the custom menu that appears when the spreadsheet opens.
 */

function onOpen() {
  SpreadsheetApp.getUi()
    .createMenu('ELA Reporting')
    .addItem('1. Set up workbook', 'buildAll')
    .addSeparator()
    .addSubMenu(SpreadsheetApp.getUi().createMenu('2. Answer-sheet Forms (optional)')
      .addItem('Create Form A (Pre-Test)', 'createFormA')
      .addItem('Create Form B (Post-Test)', 'createFormB')
      .addSeparator()
      .addItem('Show Form links', 'showFormLinks'))
    .addItem('3. Score Form responses now', 'scoreAllForms')
    .addSeparator()
    .addItem('4. Generate student reports (Google Doc)', 'generateStudentReports')
    .addSeparator()
    .addSubMenu(SpreadsheetApp.getUi().createMenu('Checks')
      .addItem('Run scoring self-test', 'runScoringSelfTest')
      .addItem('About this workbook', 'showAbout'))
    .addToUi();
}

function runScoringSelfTest() {
  var res = testScoringRules();
  var ui = SpreadsheetApp.getUi();
  var failed = res.results.filter(function (l) { return l.indexOf('FAIL') === 0; });
  var msg = res.pass + ' checks passed, ' + res.fail + ' failed.\n\n';
  msg += failed.length ? failed.join('\n') :
    'Partial-credit rules, blueprint point totals, and both answer keys are consistent.';
  ui.alert('Scoring self-test', msg, ui.ButtonSet.OK);
}

function showAbout() {
  SpreadsheetApp.getUi().alert('Grade 7 ELA Pre/Post Reporting',
    'Built to the Georgia Milestones Grade 7 ELA blueprint: 60 points, 41 scored columns, ' +
    'seven reporting categories weighted exactly as the state weights them.\n\n' +
    'Three cautions worth repeating:\n\n' +
    '• A category rests on as few as 6 points. Confirm a low category against student work before acting.\n\n' +
    '• A gain below the reliable-change threshold (Settings B18) may be measurement noise, not growth.\n\n' +
    '• Cut scores were set by content review, not a state standard-setting panel. They are instructional ' +
    'triage, not a prediction of a Georgia Milestones level.\n\n' +
    'Full documentation lives with the assessment files in docs/.',
    SpreadsheetApp.getUi().ButtonSet.OK);
}
