#!/usr/bin/env python3
"""
Concatenate the seven Apps Script source files into one paste-ready .gs bundle.

Apps Script evaluates a project's files in order, sharing one global scope, so
the bundle must keep Config first (its `var` assignments are read by the files
that follow). Function declarations hoist within the single combined file, so
cross-references between the former files resolve regardless of position.

Run this after editing any .gs file so the bundle never drifts from its sources:

    python tools/build_apps_script_bundle.py
"""

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "google-apps-script"
OUT = SRC / "ELA-Reporting-ALL-IN-ONE.gs"

# Order matters: Config defines the vars every other file reads at load time.
ORDER = [
    "Config.gs",
    "BuildSheets.gs",
    "BuildSheets2.gs",
    "Scoring.gs",
    "FormBuilder.gs",
    "Reports.gs",
    "Menu.gs",
]

HEADER = """/**
 * ==========================================================================
 *  GRADE 7 ELA PRE/POST — REPORTING & AUTO-SCORING
 *  Single-file build. Paste this whole file into ONE Apps Script file.
 * ==========================================================================
 *
 *  SETUP
 *  1. Create a Google Sheet. Extensions > Apps Script.
 *  2. Delete whatever is in Code.gs and paste this entire file in its place.
 *  3. Click the gear (Project Settings) and tick
 *     "Show appsscript.json manifest file in editor".
 *     Open appsscript.json and paste in the manifest from
 *     google-apps-script/appsscript.json. (That file is JSON, not script —
 *     it declares which permissions the project needs.)
 *  4. Save, then reload the spreadsheet tab. An "ELA Reporting" menu appears.
 *  5. Run: ELA Reporting > 1. Set up workbook.
 *     Google asks you to authorize on first run. If you see an
 *     "unverified app" screen, click Advanced > Go to (project name).
 *     It is your own script; the permissions are limited to this
 *     spreadsheet, Google Forms, and Google Docs.
 *
 *  WARNING: "Set up workbook" rebuilds all ten sheets and ERASES any scores
 *  already entered. It asks first. Duplicate the spreadsheet before re-running
 *  it once you have live data.
 *
 *  Built to the Georgia Milestones Grade 7 ELA Assessment Blueprint.
 *  Generated by tools/build_apps_script_bundle.py — do not edit this file by
 *  hand; edit the individual .gs sources and re-run that script.
 * ==========================================================================
 */

"""


def main() -> None:
    parts = [HEADER]
    for name in ORDER:
        path = SRC / name
        if not path.exists():
            sys.exit(f"Missing source file: {path}")
        body = path.read_text(encoding="utf-8").rstrip()
        rule = "=" * 70
        parts.append(
            f"\n// {rule}\n"
            f"// ===  {name}\n"
            f"// {rule}\n\n{body}\n"
        )

    OUT.write_text("".join(parts), encoding="utf-8")

    size = OUT.stat().st_size
    lines = OUT.read_text(encoding="utf-8").count("\n") + 1
    print(f"wrote {OUT.relative_to(ROOT)}  ({size // 1024} KB, {lines} lines, {len(ORDER)} sources)")

    # Syntax-check the bundle if Node is available.
    node = subprocess.run(["which", "node"], capture_output=True, text=True)
    if node.returncode == 0:
        tmp = Path("/tmp/_bundle_check.js")
        tmp.write_text(OUT.read_text(encoding="utf-8"), encoding="utf-8")
        chk = subprocess.run(["node", "--check", str(tmp)], capture_output=True, text=True)
        if chk.returncode == 0:
            print("syntax check: OK — bundle parses as valid JavaScript")
        else:
            print("syntax check: FAILED")
            print(chk.stderr[:2000])
            sys.exit(1)
    else:
        print("syntax check: skipped (node not found)")


if __name__ == "__main__":
    main()
